- exercise_inol: 0.9142857142857143
  scheme: 4x8@65%
  set_inol: '0.228571428571'
  volume: '32'
  week: 1
  weight: '26.0'
  weight_olympic: '26.0'
  weight_powerlifting: '25.0'
- exercise_inol: 0.9333333333333333
  scheme: 4x7@70%
  set_inol: '0.233333333333'
  volume: '28'
  week: 2
  weight: '28.0'
  weight_olympic: '28.0'
  weight_powerlifting: '27.5'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  week: 3
  weight: '30.0'
  weight_olympic: '30.0'
  weight_powerlifting: '30.0'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  week: 4
  weight: '32.0'
  weight_olympic: '32.0'
  weight_powerlifting: '32.5'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '34.0'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '38.0'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
