- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '26.0'
  weight_olympic: '26.0'
  weight_powerlifting: '25.0'
- exercise_inol: 1.0
  scheme: 6x5@70%
  set_inol: '0.166666666667'
  volume: '30'
  week: 2
  weight: '28.0'
  weight_olympic: '28.0'
  weight_powerlifting: '27.5'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '30.0'
  weight_olympic: '30.0'
  weight_powerlifting: '30.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '32.0'
  weight_olympic: '32.0'
  weight_powerlifting: '32.5'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '34.0'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '38.0'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
