- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '77.35'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '83.3'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '89.25'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '95.2'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '101.15'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '107.1'
  weight_olympic: '107.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '113.05'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
