- exercise_inol: 0.30000000000000004
  scheme: 3x3@70%
  set_inol: '0.1'
  volume: '9'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.3333333333333333
  scheme: 5x2@70%
  set_inol: '0.0666666666667'
  volume: '10'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.3333333333333333
  scheme: 2x5@70%
  set_inol: '0.166666666667'
  volume: '10'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 3x4@70%
  set_inol: '0.133333333333'
  volume: '12'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4666666666666667
  scheme: 7x2@70%
  set_inol: '0.0666666666667'
  volume: '14'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.5
  scheme: 5x3@70%
  set_inol: '0.1'
  volume: '15'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.5
  scheme: 3x5@70%
  set_inol: '0.166666666667'
  volume: '15'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.5333333333333333
  scheme: 8x2@70%
  set_inol: '0.0666666666667'
  volume: '16'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x4@70%
  set_inol: '0.133333333333'
  volume: '16'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6
  scheme: 9x2@70%
  set_inol: '0.0666666666667'
  volume: '18'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x3@70%
  set_inol: '0.1'
  volume: '18'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6666666666666666
  scheme: 10x2@70%
  set_inol: '0.0666666666667'
  volume: '20'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x4@70%
  set_inol: '0.133333333333'
  volume: '20'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6666666666666666
  scheme: 4x5@70%
  set_inol: '0.166666666667'
  volume: '20'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.7000000000000001
  scheme: 7x3@70%
  set_inol: '0.1'
  volume: '21'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8333333333333333
  scheme: 5x5@70%
  set_inol: '0.166666666667'
  volume: '25'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.9
  scheme: 9x3@70%
  set_inol: '0.1'
  volume: '27'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.9333333333333333
  scheme: 7x4@70%
  set_inol: '0.133333333333'
  volume: '28'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.0
  scheme: 10x3@70%
  set_inol: '0.1'
  volume: '30'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.0
  scheme: 6x5@70%
  set_inol: '0.166666666667'
  volume: '30'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.0666666666666667
  scheme: 8x4@70%
  set_inol: '0.133333333333'
  volume: '32'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.1666666666666665
  scheme: 7x5@70%
  set_inol: '0.166666666667'
  volume: '35'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.2
  scheme: 9x4@70%
  set_inol: '0.133333333333'
  volume: '36'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.3333333333333333
  scheme: 10x4@70%
  set_inol: '0.133333333333'
  volume: '40'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.3333333333333333
  scheme: 8x5@70%
  set_inol: '0.166666666667'
  volume: '40'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.5
  scheme: 9x5@70%
  set_inol: '0.166666666667'
  volume: '45'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 1.6666666666666665
  scheme: 10x5@70%
  set_inol: '0.166666666667'
  volume: '50'
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
