- exercise_inol: 0.30000000000000004
  scheme: 3x2@80%
  set_inol: '0.1'
  volume: '6'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.35
  scheme: 1x7@80%
  set_inol: '0.35'
  volume: '7'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 2x4@80%
  set_inol: '0.2'
  volume: '8'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 1x8@80%
  set_inol: '0.4'
  volume: '8'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.45
  scheme: 1x9@80%
  set_inol: '0.45'
  volume: '9'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5
  scheme: 2x5@80%
  set_inol: '0.25'
  volume: '10'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6
  scheme: 2x6@80%
  set_inol: '0.3'
  volume: '12'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x4@80%
  set_inol: '0.2'
  volume: '12'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.7
  scheme: 2x7@80%
  set_inol: '0.35'
  volume: '14'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.75
  scheme: 3x5@80%
  set_inol: '0.25'
  volume: '15'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8
  scheme: 2x8@80%
  set_inol: '0.4'
  volume: '16'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x6@80%
  set_inol: '0.3'
  volume: '18'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.9
  scheme: 2x9@80%
  set_inol: '0.45'
  volume: '18'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.0
  scheme: 4x5@80%
  set_inol: '0.25'
  volume: '20'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.0499999999999998
  scheme: 3x7@80%
  set_inol: '0.35'
  volume: '21'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.2
  scheme: 4x6@80%
  set_inol: '0.3'
  volume: '24'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x4@80%
  set_inol: '0.2'
  volume: '24'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x8@80%
  set_inol: '0.4'
  volume: '24'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.25
  scheme: 5x5@80%
  set_inol: '0.25'
  volume: '25'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.35
  scheme: 3x9@80%
  set_inol: '0.45'
  volume: '27'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.4
  scheme: 4x7@80%
  set_inol: '0.35'
  volume: '28'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.5
  scheme: 6x5@80%
  set_inol: '0.25'
  volume: '30'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.5
  scheme: 5x6@80%
  set_inol: '0.3'
  volume: '30'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.6
  scheme: 4x8@80%
  set_inol: '0.4'
  volume: '32'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.75
  scheme: 5x7@80%
  set_inol: '0.35'
  volume: '35'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.7999999999999998
  scheme: 6x6@80%
  set_inol: '0.3'
  volume: '36'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.8
  scheme: 4x9@80%
  set_inol: '0.45'
  volume: '36'
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
