- exercise_inol: 0.4
  scheme: 2x7@65%
  set_inol: '0.2'
  volume: '14'
  week: 1
  weight: '30.55'
  weight_olympic: '31.0'
  weight_powerlifting: '30.0'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 2
  weight: '32.9'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '35.25'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '37.6'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 5
  weight: '39.95'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '42.3'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '44.65'
  weight_olympic: '45.0'
  weight_powerlifting: '45.0'
