- exercise_inol: 0.888888888888889
  scheme: 5x8@55%
  set_inol: '0.177777777778'
  volume: '40'
  week: 1
  weight: '93.5'
  weight_olympic: '94.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.9
  scheme: 4x9@60%
  set_inol: '0.225'
  volume: '36'
  week: 2
  weight: '102.0'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.9142857142857143
  scheme: 4x8@65%
  set_inol: '0.228571428571'
  volume: '32'
  week: 3
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x9@70%
  set_inol: '0.3'
  volume: '27'
  week: 4
  weight: '119.0'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  week: 5
  weight: '127.5'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.9
  scheme: 2x9@80%
  set_inol: '0.45'
  volume: '18'
  week: 6
  weight: '136.0'
  weight_olympic: '136.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.9333333333333333
  scheme: 2x7@85%
  set_inol: '0.466666666667'
  volume: '14'
  week: 7
  weight: '144.5'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 8
  weight: '153.0'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 9
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
