- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '107.25'
  weight_olympic: '107.0'
  weight_powerlifting: '107.5'
- exercise_inol: 1.0
  scheme: 6x5@70%
  set_inol: '0.166666666667'
  volume: '30'
  week: 2
  weight: '115.5'
  weight_olympic: '115.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '123.75'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '132.0'
  weight_olympic: '132.0'
  weight_powerlifting: '132.5'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '140.25'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '148.5'
  weight_olympic: '149.0'
  weight_powerlifting: '147.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '156.75'
  weight_olympic: '157.0'
  weight_powerlifting: '157.5'
