- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '120.9'
  weight_olympic: '121.0'
  weight_powerlifting: '120.0'
- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '130.2'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '139.5'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '148.8'
  weight_olympic: '149.0'
  weight_powerlifting: '150.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '158.1'
  weight_olympic: '158.0'
  weight_powerlifting: '157.5'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '167.4'
  weight_olympic: '167.0'
  weight_powerlifting: '167.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '176.7'
  weight_olympic: '177.0'
  weight_powerlifting: '177.5'
