- exercise_inol: 0.9230769230769231
  scheme: 6x5@67.5%
  set_inol: '0.153846153846'
  volume: '30'
  week: 1
  weight: '64.125'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.9818181818181818
  scheme: 3x9@72.5%
  set_inol: '0.327272727273'
  volume: '27'
  week: 2
  weight: '68.875'
  weight_olympic: '69.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.9333333333333333
  scheme: 3x7@77.5%
  set_inol: '0.311111111111'
  volume: '21'
  week: 3
  weight: '73.625'
  weight_olympic: '74.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.9142857142857143
  scheme: 4x4@82.5%
  set_inol: '0.228571428571'
  volume: '16'
  week: 4
  weight: '78.375'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.96
  scheme: 6x2@87.5%
  set_inol: '0.16'
  volume: '12'
  week: 5
  weight: '83.125'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.0666666666666667
  scheme: 4x2@92.5%
  set_inol: '0.266666666667'
  volume: '8'
  week: 6
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 2x1@97.5%
  set_inol: '0.4'
  volume: '2'
  week: 7
  weight: '92.625'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
