- exercise_inol: 0.4
  scheme: 3x1@92.5%
  set_inol: '0.133333333333'
  volume: '3'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.4
  scheme: 1x3@92.5%
  set_inol: '0.4'
  volume: '3'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.5333333333333333
  scheme: 2x2@92.5%
  set_inol: '0.266666666667'
  volume: '4'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x1@92.5%
  set_inol: '0.133333333333'
  volume: '5'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 6x1@92.5%
  set_inol: '0.133333333333'
  volume: '6'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 3x2@92.5%
  set_inol: '0.266666666667'
  volume: '6'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 2x3@92.5%
  set_inol: '0.4'
  volume: '6'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.0666666666666667
  scheme: 4x2@92.5%
  set_inol: '0.266666666667'
  volume: '8'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.2000000000000002
  scheme: 3x3@92.5%
  set_inol: '0.4'
  volume: '9'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.3333333333333333
  scheme: 5x2@92.5%
  set_inol: '0.266666666667'
  volume: '10'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.6
  scheme: 6x2@92.5%
  set_inol: '0.266666666667'
  volume: '12'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.6
  scheme: 4x3@92.5%
  set_inol: '0.4'
  volume: '12'
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
