- exercise_inol: 0.4
  scheme: 1x1@97.5%
  set_inol: '0.4'
  volume: '1'
  weight: '92.625'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.8
  scheme: 2x1@97.5%
  set_inol: '0.4'
  volume: '2'
  weight: '92.625'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
- exercise_inol: 1.2000000000000002
  scheme: 3x1@97.5%
  set_inol: '0.4'
  volume: '3'
  weight: '92.625'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
- exercise_inol: 1.6
  scheme: 4x1@97.5%
  set_inol: '0.4'
  volume: '4'
  weight: '92.625'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
