- exercise_inol: 1.2
  scheme: 4x9@70.0%
  set_inol: '0.3'
  volume: '36'
  week: 1
  weight: '70.0'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x11@72.5%
  set_inol: '0.4'
  volume: '33'
  week: 2
  weight: '72.5'
  weight_olympic: '73.0'
  weight_powerlifting: '72.5'
- exercise_inol: 1.2
  scheme: 5x6@75.0%
  set_inol: '0.24'
  volume: '30'
  week: 3
  weight: '75.0'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x9@77.5%
  set_inol: '0.4'
  volume: '27'
  week: 4
  weight: '77.5'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.2
  scheme: 4x6@80.0%
  set_inol: '0.3'
  volume: '24'
  week: 5
  weight: '80.0'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x7@82.5%
  set_inol: '0.4'
  volume: '21'
  week: 6
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.2000000000000002
  scheme: 6x3@85.0%
  set_inol: '0.2'
  volume: '18'
  week: 7
  weight: '85.0'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 1.2
  scheme: 5x3@87.5%
  set_inol: '0.24'
  volume: '15'
  week: 8
  weight: '87.5'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.2
  scheme: 4x3@90.0%
  set_inol: '0.3'
  volume: '12'
  week: 9
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x3@92.5%
  set_inol: '0.4'
  volume: '9'
  week: 10
  weight: '92.5'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
- exercise_inol: 1.2000000000000002
  scheme: 6x1@95.0%
  set_inol: '0.2'
  volume: '6'
  week: 11
  weight: '95.0'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x1@97.5%
  set_inol: '0.4'
  volume: '3'
  week: 12
  weight: '97.5'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
