- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '68.25'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '73.5'
  weight_olympic: '74.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.8
  scheme: 4x5@75%
  set_inol: '0.2'
  volume: '20'
  week: 3
  weight: '78.75'
  weight_olympic: '79.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '84.0'
  weight_olympic: '84.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '89.25'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '94.5'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '99.75'
  weight_olympic: '100.0'
  weight_powerlifting: '100.0'
