- exercise_inol: 0.34285714285714286
  scheme: 6x1@82.5%
  set_inol: '0.0571428571429'
  volume: '6'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.34285714285714286
  scheme: 3x2@82.5%
  set_inol: '0.114285714286'
  volume: '6'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.34285714285714286
  scheme: 2x3@82.5%
  set_inol: '0.171428571429'
  volume: '6'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.34285714285714286
  scheme: 1x6@82.5%
  set_inol: '0.342857142857'
  volume: '6'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.4
  scheme: 1x7@82.5%
  set_inol: '0.4'
  volume: '7'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.45714285714285713
  scheme: 4x2@82.5%
  set_inol: '0.114285714286'
  volume: '8'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.45714285714285713
  scheme: 2x4@82.5%
  set_inol: '0.228571428571'
  volume: '8'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.45714285714285713
  scheme: 1x8@82.5%
  set_inol: '0.457142857143'
  volume: '8'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.5142857142857142
  scheme: 3x3@82.5%
  set_inol: '0.171428571429'
  volume: '9'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.5714285714285714
  scheme: 5x2@82.5%
  set_inol: '0.114285714286'
  volume: '10'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.5714285714285714
  scheme: 2x5@82.5%
  set_inol: '0.285714285714'
  volume: '10'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6857142857142857
  scheme: 6x2@82.5%
  set_inol: '0.114285714286'
  volume: '12'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6857142857142857
  scheme: 4x3@82.5%
  set_inol: '0.171428571429'
  volume: '12'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6857142857142857
  scheme: 3x4@82.5%
  set_inol: '0.228571428571'
  volume: '12'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6857142857142857
  scheme: 2x6@82.5%
  set_inol: '0.342857142857'
  volume: '12'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8
  scheme: 2x7@82.5%
  set_inol: '0.4'
  volume: '14'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8571428571428571
  scheme: 3x5@82.5%
  set_inol: '0.285714285714'
  volume: '15'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8571428571428572
  scheme: 5x3@82.5%
  set_inol: '0.171428571429'
  volume: '15'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.9142857142857143
  scheme: 4x4@82.5%
  set_inol: '0.228571428571'
  volume: '16'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.9142857142857143
  scheme: 2x8@82.5%
  set_inol: '0.457142857143'
  volume: '16'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.0285714285714285
  scheme: 6x3@82.5%
  set_inol: '0.171428571429'
  volume: '18'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.0285714285714285
  scheme: 3x6@82.5%
  set_inol: '0.342857142857'
  volume: '18'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.1428571428571428
  scheme: 5x4@82.5%
  set_inol: '0.228571428571'
  volume: '20'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.1428571428571428
  scheme: 4x5@82.5%
  set_inol: '0.285714285714'
  volume: '20'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.2000000000000002
  scheme: 3x7@82.5%
  set_inol: '0.4'
  volume: '21'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.3714285714285714
  scheme: 6x4@82.5%
  set_inol: '0.228571428571'
  volume: '24'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.3714285714285714
  scheme: 4x6@82.5%
  set_inol: '0.342857142857'
  volume: '24'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.3714285714285714
  scheme: 3x8@82.5%
  set_inol: '0.457142857143'
  volume: '24'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.4285714285714284
  scheme: 5x5@82.5%
  set_inol: '0.285714285714'
  volume: '25'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.6
  scheme: 4x7@82.5%
  set_inol: '0.4'
  volume: '28'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.7142857142857142
  scheme: 6x5@82.5%
  set_inol: '0.285714285714'
  volume: '30'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.7142857142857144
  scheme: 5x6@82.5%
  set_inol: '0.342857142857'
  volume: '30'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 1.8285714285714285
  scheme: 4x8@82.5%
  set_inol: '0.457142857143'
  volume: '32'
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
