- exercise_inol: 0.8571428571428571
  scheme: 3x5@82.5%
  set_inol: '0.285714285714'
  volume: '15'
  week: 1
  weight: '130.35'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.8
  scheme: 4x3@85.0%
  set_inol: '0.2'
  volume: '12'
  week: 2
  weight: '134.3'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.8
  scheme: 5x2@87.5%
  set_inol: '0.16'
  volume: '10'
  week: 3
  weight: '138.25'
  weight_olympic: '138.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.8
  scheme: 4x2@90.0%
  set_inol: '0.2'
  volume: '8'
  week: 4
  weight: '142.2'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 3x2@92.5%
  set_inol: '0.266666666667'
  volume: '6'
  week: 5
  weight: '146.15'
  weight_olympic: '146.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.8
  scheme: 4x1@95.0%
  set_inol: '0.2'
  volume: '4'
  week: 6
  weight: '150.1'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
