- exercise_inol: 0.45714285714285713
  scheme: 4x4@65%
  set_inol: '0.114285714286'
  volume: '16'
  week: 1
  weight: '107.25'
  weight_olympic: '107.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.4666666666666667
  scheme: 2x7@70%
  set_inol: '0.233333333333'
  volume: '14'
  week: 2
  weight: '115.5'
  weight_olympic: '115.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  week: 3
  weight: '123.75'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  week: 4
  weight: '132.0'
  weight_olympic: '132.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  week: 5
  weight: '140.25'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '148.5'
  weight_olympic: '149.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '156.75'
  weight_olympic: '157.0'
  weight_powerlifting: '157.5'
