- exercise_inol: 0.7714285714285714
  scheme: 3x9@65%
  set_inol: '0.257142857143'
  volume: '27'
  week: 1
  weight: '122.2'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '131.6'
  weight_olympic: '132.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.72
  scheme: 3x6@75%
  set_inol: '0.24'
  volume: '18'
  week: 3
  weight: '141.0'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  week: 4
  weight: '150.4'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '159.8'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '169.2'
  weight_olympic: '169.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '178.6'
  weight_olympic: '179.0'
  weight_powerlifting: '177.5'
