- exercise_inol: 0.9142857142857143
  scheme: 4x8@65%
  set_inol: '0.228571428571'
  volume: '32'
  week: 1
  weight: '42.25'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x9@70%
  set_inol: '0.3'
  volume: '27'
  week: 2
  weight: '45.5'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  week: 3
  weight: '48.75'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.9
  scheme: 2x9@80%
  set_inol: '0.45'
  volume: '18'
  week: 4
  weight: '52.0'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.9333333333333333
  scheme: 2x7@85%
  set_inol: '0.466666666667'
  volume: '14'
  week: 5
  weight: '55.25'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 6
  weight: '58.5'
  weight_olympic: '59.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '61.75'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
