- exercise_inol: 0.9142857142857143
  scheme: 8x4@65%
  set_inol: '0.114285714286'
  volume: '32'
  week: 1
  weight: '123.5'
  weight_olympic: '124.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.9333333333333333
  scheme: 7x4@70%
  set_inol: '0.133333333333'
  volume: '28'
  week: 2
  weight: '133.0'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.96
  scheme: 8x3@75%
  set_inol: '0.12'
  volume: '24'
  week: 3
  weight: '142.5'
  weight_olympic: '143.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  week: 4
  weight: '152.0'
  weight_olympic: '152.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.9333333333333333
  scheme: 7x2@85%
  set_inol: '0.133333333333'
  volume: '14'
  week: 5
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 6
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '180.5'
  weight_olympic: '181.0'
  weight_powerlifting: '180.0'
