- exercise_inol: 0.30000000000000004
  scheme: 3x3@70%
  set_inol: '0.1'
  volume: '9'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.3333333333333333
  scheme: 5x2@70%
  set_inol: '0.0666666666667'
  volume: '10'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5
  scheme: 5x3@70%
  set_inol: '0.1'
  volume: '15'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x3@70%
  set_inol: '0.1'
  volume: '18'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
