- exercise_inol: 0.32
  scheme: 4x2@75%
  set_inol: '0.08'
  volume: '8'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.36
  scheme: 3x3@75%
  set_inol: '0.12'
  volume: '9'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.48
  scheme: 6x2@75%
  set_inol: '0.08'
  volume: '12'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
