- exercise_inol: 0.5142857142857142
  scheme: 6x3@65%
  set_inol: '0.0857142857143'
  volume: '18'
  week: 1
  weight: '35.1'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x3@70%
  set_inol: '0.1'
  volume: '18'
  week: 2
  weight: '37.8'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '48.6'
  weight_olympic: '49.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '51.3'
  weight_olympic: '51.0'
  weight_powerlifting: '52.5'
