- exercise_inol: 0.64
  scheme: 6x4@62.5%
  set_inol: '0.106666666667'
  volume: '24'
  week: 1
  weight: '28.125'
  weight_olympic: '28.0'
  weight_powerlifting: '27.5'
- exercise_inol: 0.6153846153846154
  scheme: 5x4@67.5%
  set_inol: '0.123076923077'
  volume: '20'
  week: 2
  weight: '30.375'
  weight_olympic: '30.0'
  weight_powerlifting: '30.0'
- exercise_inol: 0.5818181818181818
  scheme: 4x4@72.5%
  set_inol: '0.145454545455'
  volume: '16'
  week: 3
  weight: '32.625'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.5333333333333333
  scheme: 6x2@77.5%
  set_inol: '0.0888888888889'
  volume: '12'
  week: 4
  weight: '34.875'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5714285714285714
  scheme: 5x2@82.5%
  set_inol: '0.114285714286'
  volume: '10'
  week: 5
  weight: '37.125'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.64
  scheme: 4x2@87.5%
  set_inol: '0.16'
  volume: '8'
  week: 6
  weight: '39.375'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 7
  weight: '41.625'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
