- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 1
  weight: '115.375'
  weight_olympic: '115.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x3@70%
  set_inol: '0.1'
  volume: '18'
  week: 2
  weight: '124.25'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '133.125'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '142.0'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '150.875'
  weight_olympic: '151.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '159.75'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '168.625'
  weight_olympic: '169.0'
  weight_powerlifting: '167.5'
