- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '115.375'
  weight_olympic: '115.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '124.25'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '133.125'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '142.0'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '150.875'
  weight_olympic: '151.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '159.75'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '168.625'
  weight_olympic: '169.0'
  weight_powerlifting: '167.5'
