- exercise_inol: 1.0
  scheme: 7x5@65%
  set_inol: '0.142857142857'
  volume: '35'
  week: 1
  weight: '113.75'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.0
  scheme: 10x3@70%
  set_inol: '0.1'
  volume: '30'
  week: 2
  weight: '122.5'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '131.25'
  weight_olympic: '131.0'
  weight_powerlifting: '132.5'
- exercise_inol: 1.0
  scheme: 10x2@80%
  set_inol: '0.1'
  volume: '20'
  week: 4
  weight: '140.0'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '148.75'
  weight_olympic: '149.0'
  weight_powerlifting: '150.0'
- exercise_inol: 1.0
  scheme: 10x1@90%
  set_inol: '0.1'
  volume: '10'
  week: 6
  weight: '157.5'
  weight_olympic: '158.0'
  weight_powerlifting: '157.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '166.25'
  weight_olympic: '166.0'
  weight_powerlifting: '167.5'
