- exercise_inol: 0.45714285714285713
  scheme: 4x4@65%
  set_inol: '0.114285714286'
  volume: '16'
  week: 1
  weight: '29.25'
  weight_olympic: '29.0'
  weight_powerlifting: '30.0'
- exercise_inol: 0.5
  scheme: 5x3@70%
  set_inol: '0.1'
  volume: '15'
  week: 2
  weight: '31.5'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  week: 3
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  week: 4
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85%
  set_inol: '0.133333333333'
  volume: '8'
  week: 5
  weight: '38.25'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5
  scheme: 5x1@90%
  set_inol: '0.1'
  volume: '5'
  week: 6
  weight: '40.5'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '42.75'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
