- exercise_inol: 0.5454545454545454
  scheme: 5x3@72.5%
  set_inol: '0.109090909091'
  volume: '15'
  week: 1
  weight: '32.625'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x3@77.5%
  set_inol: '0.133333333333'
  volume: '12'
  week: 2
  weight: '34.875'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5142857142857142
  scheme: 3x3@82.5%
  set_inol: '0.171428571429'
  volume: '9'
  week: 3
  weight: '37.125'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.48
  scheme: 3x2@87.5%
  set_inol: '0.16'
  volume: '6'
  week: 4
  weight: '39.375'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 5
  weight: '41.625'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
