- exercise_inol: 0.4
  scheme: 3x4@70%
  set_inol: '0.133333333333'
  volume: '12'
  week: 1
  weight: '56.0'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 2x5@75%
  set_inol: '0.2'
  volume: '10'
  week: 2
  weight: '60.0'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 2x4@80%
  set_inol: '0.2'
  volume: '8'
  week: 3
  weight: '64.0'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.4
  scheme: 2x3@85%
  set_inol: '0.2'
  volume: '6'
  week: 4
  weight: '68.0'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.4
  scheme: 2x2@90%
  set_inol: '0.2'
  volume: '4'
  week: 5
  weight: '72.0'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 6
  weight: '76.0'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
