- exercise_inol: 0.6
  scheme: 9x3@55%
  set_inol: '0.0666666666667'
  volume: '27'
  week: 1
  weight: '85.8'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.6
  scheme: 8x3@60%
  set_inol: '0.075'
  volume: '24'
  week: 2
  weight: '93.6'
  weight_olympic: '94.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 3
  weight: '101.4'
  weight_olympic: '101.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.6
  scheme: 9x2@70%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 4
  weight: '109.2'
  weight_olympic: '109.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 5
  weight: '117.0'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 6
  weight: '124.8'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.6
  scheme: 9x1@85%
  set_inol: '0.0666666666667'
  volume: '9'
  week: 7
  weight: '132.6'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 8
  weight: '140.4'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 9
  weight: '148.2'
  weight_olympic: '148.0'
  weight_powerlifting: '147.5'
