- exercise_inol: 0.4
  scheme: 6x3@55%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 1
  weight: '44.0'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  week: 2
  weight: '48.0'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.39999999999999997
  scheme: 7x2@65%
  set_inol: '0.0571428571429'
  volume: '14'
  week: 3
  weight: '52.0'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 4
  weight: '56.0'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 5
  weight: '60.0'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '64.0'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 7
  weight: '68.0'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 8
  weight: '72.0'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 9
  weight: '76.0'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
