- exercise_inol: 0.75
  scheme: 3x10@60%
  set_inol: '0.25'
  volume: '30'
  week: 1
  weight: '117.0'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.7714285714285714
  scheme: 3x9@65%
  set_inol: '0.257142857143'
  volume: '27'
  week: 2
  weight: '126.75'
  weight_olympic: '127.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.8
  scheme: 3x8@70%
  set_inol: '0.266666666667'
  volume: '24'
  week: 3
  weight: '136.5'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.72
  scheme: 2x9@75%
  set_inol: '0.36'
  volume: '18'
  week: 4
  weight: '146.25'
  weight_olympic: '146.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.75
  scheme: 3x5@80%
  set_inol: '0.25'
  volume: '15'
  week: 5
  weight: '156.0'
  weight_olympic: '156.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.8
  scheme: 3x4@85%
  set_inol: '0.266666666667'
  volume: '12'
  week: 6
  weight: '165.75'
  weight_olympic: '166.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 7
  weight: '175.5'
  weight_olympic: '176.0'
  weight_powerlifting: '175.0'
