- exercise_inol: 0.7714285714285714
  scheme: 3x9@65%
  set_inol: '0.257142857143'
  volume: '27'
  week: 1
  weight: '123.5'
  weight_olympic: '124.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '133.0'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.72
  scheme: 3x6@75%
  set_inol: '0.24'
  volume: '18'
  week: 3
  weight: '142.5'
  weight_olympic: '143.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  week: 4
  weight: '152.0'
  weight_olympic: '152.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '180.5'
  weight_olympic: '181.0'
  weight_powerlifting: '180.0'
