- exercise_inol: 0.7714285714285714
  scheme: 3x9@65%
  set_inol: '0.257142857143'
  volume: '27'
  week: 1
  weight: '108.875'
  weight_olympic: '109.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '117.25'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.72
  scheme: 3x6@75%
  set_inol: '0.24'
  volume: '18'
  week: 3
  weight: '125.625'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  week: 4
  weight: '134.0'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '142.375'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '150.75'
  weight_olympic: '151.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '159.125'
  weight_olympic: '159.0'
  weight_powerlifting: '160.0'
