- exercise_inol: 0.9142857142857143
  scheme: 4x8@65%
  set_inol: '0.228571428571'
  volume: '32'
  week: 1
  weight: '102.375'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x9@70%
  set_inol: '0.3'
  volume: '27'
  week: 2
  weight: '110.25'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  week: 3
  weight: '118.125'
  weight_olympic: '118.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  week: 4
  weight: '126.0'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '133.875'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 6
  weight: '141.75'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '149.625'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
