- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '59.8'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '64.4'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '69.0'
  weight_olympic: '69.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '73.6'
  weight_olympic: '74.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '78.2'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '82.8'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '87.4'
  weight_olympic: '87.0'
  weight_powerlifting: '87.5'
