- exercise_inol: 1.2000000000000002
  scheme: 6x7@65%
  set_inol: '0.2'
  volume: '42'
  week: 1
  weight: '53.95'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.2
  scheme: 4x9@70%
  set_inol: '0.3'
  volume: '36'
  week: 2
  weight: '58.1'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 1.2
  scheme: 5x6@75%
  set_inol: '0.24'
  volume: '30'
  week: 3
  weight: '62.25'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 1.2
  scheme: 4x6@80%
  set_inol: '0.3'
  volume: '24'
  week: 4
  weight: '66.4'
  weight_olympic: '66.0'
  weight_powerlifting: '67.5'
- exercise_inol: 1.2000000000000002
  scheme: 6x3@85%
  set_inol: '0.2'
  volume: '18'
  week: 5
  weight: '70.55'
  weight_olympic: '71.0'
  weight_powerlifting: '70.0'
- exercise_inol: 1.2
  scheme: 4x3@90%
  set_inol: '0.3'
  volume: '12'
  week: 6
  weight: '74.7'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x1@95%
  set_inol: '0.2'
  volume: '6'
  week: 7
  weight: '78.85'
  weight_olympic: '79.0'
  weight_powerlifting: '80.0'
