- exercise_inol: 0.6857142857142857
  scheme: 6x4@65%
  set_inol: '0.114285714286'
  volume: '24'
  week: 1
  weight: '53.95'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.7
  scheme: 3x7@70%
  set_inol: '0.233333333333'
  volume: '21'
  week: 2
  weight: '58.1'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  week: 3
  weight: '62.25'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.7
  scheme: 2x7@80%
  set_inol: '0.35'
  volume: '14'
  week: 4
  weight: '66.4'
  weight_olympic: '66.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  week: 5
  weight: '70.55'
  weight_olympic: '71.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '74.7'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '78.85'
  weight_olympic: '79.0'
  weight_powerlifting: '80.0'
