- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '49.4'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '53.2'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '57.0'
  weight_olympic: '57.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '60.8'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '64.6'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '68.4'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '72.2'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
