- exercise_inol: 0.5818181818181818
  scheme: 4x4@72.5%
  set_inol: '0.145454545455'
  volume: '16'
  week: 1
  weight: '60.175'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6222222222222222
  scheme: 2x7@77.5%
  set_inol: '0.311111111111'
  volume: '14'
  week: 2
  weight: '64.325'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.5714285714285714
  scheme: 5x2@82.5%
  set_inol: '0.114285714286'
  volume: '10'
  week: 3
  weight: '68.475'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.64
  scheme: 4x2@87.5%
  set_inol: '0.16'
  volume: '8'
  week: 4
  weight: '72.625'
  weight_olympic: '73.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 5
  weight: '76.775'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
