- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '57.85'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '62.3'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '66.75'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '71.2'
  weight_olympic: '71.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '75.65'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '80.1'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '84.55'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
