- exercise_inol: 0.4
  scheme: 3x1@92.5%
  set_inol: '0.133333333333'
  volume: '3'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5333333333333333
  scheme: 2x2@92.5%
  set_inol: '0.266666666667'
  volume: '4'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x1@92.5%
  set_inol: '0.133333333333'
  volume: '5'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.8
  scheme: 3x2@92.5%
  set_inol: '0.266666666667'
  volume: '6'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 1.0666666666666667
  scheme: 4x2@92.5%
  set_inol: '0.266666666667'
  volume: '8'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 1.3333333333333333
  scheme: 5x2@92.5%
  set_inol: '0.266666666667'
  volume: '10'
  weight: '37.0'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
