- exercise_inol: 0.4285714285714286
  scheme: 5x3@65%
  set_inol: '0.0857142857143'
  volume: '15'
  week: 1
  weight: '28.6'
  weight_olympic: '29.0'
  weight_powerlifting: '27.5'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  week: 2
  weight: '30.8'
  weight_olympic: '31.0'
  weight_powerlifting: '30.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '33.0'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '35.2'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  week: 5
  weight: '37.4'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '39.6'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '41.8'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
