- exercise_inol: 0.3333333333333333
  scheme: 5x1@85%
  set_inol: '0.0666666666667'
  volume: '5'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 2x3@85%
  set_inol: '0.2'
  volume: '6'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85%
  set_inol: '0.133333333333'
  volume: '8'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
