- exercise_inol: 0.30000000000000004
  scheme: 3x2@80%
  set_inol: '0.1'
  volume: '6'
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  weight: '36.0'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
