- exercise_inol: 0.32
  scheme: 4x2@75%
  set_inol: '0.08'
  volume: '8'
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.36
  scheme: 3x3@75%
  set_inol: '0.12'
  volume: '9'
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
