- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '84.5'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '91.0'
  weight_olympic: '91.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '97.5'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '104.0'
  weight_olympic: '104.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '117.0'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '123.5'
  weight_olympic: '124.0'
  weight_powerlifting: '122.5'
