- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '86.125'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '92.75'
  weight_olympic: '93.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '99.375'
  weight_olympic: '99.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '106.0'
  weight_olympic: '106.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '112.625'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '119.25'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '125.875'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
