- exercise_inol: 0.4
  scheme: 6x3@55%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 1
  weight: '93.5'
  weight_olympic: '94.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  week: 2
  weight: '102.0'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.39999999999999997
  scheme: 7x2@65%
  set_inol: '0.0571428571429'
  volume: '14'
  week: 3
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 4
  weight: '119.0'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 5
  weight: '127.5'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '136.0'
  weight_olympic: '136.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 7
  weight: '144.5'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 8
  weight: '153.0'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 9
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
