- exercise_inol: 0.4
  scheme: 6x3@55%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 1
  weight: '99.0'
  weight_olympic: '99.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  week: 2
  weight: '108.0'
  weight_olympic: '108.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.39999999999999997
  scheme: 7x2@65%
  set_inol: '0.0571428571429'
  volume: '14'
  week: 3
  weight: '117.0'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 4
  weight: '126.0'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 5
  weight: '135.0'
  weight_olympic: '135.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '144.0'
  weight_olympic: '144.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 7
  weight: '153.0'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 8
  weight: '162.0'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 9
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
