- exercise_inol: 0.8
  scheme: 9x4@55%
  set_inol: '0.0888888888889'
  volume: '36'
  week: 1
  weight: '80.3'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8
  scheme: 8x4@60%
  set_inol: '0.1'
  volume: '32'
  week: 2
  weight: '87.6'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 3
  weight: '94.9'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 4
  weight: '102.2'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 5
  weight: '109.5'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 6
  weight: '116.8'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 7
  weight: '124.1'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 8
  weight: '131.4'
  weight_olympic: '131.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 9
  weight: '138.7'
  weight_olympic: '139.0'
  weight_powerlifting: '137.5'
