- exercise_inol: 0.6
  scheme: 9x3@55%
  set_inol: '0.0666666666667'
  volume: '27'
  week: 1
  weight: '80.3'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.6
  scheme: 8x3@60%
  set_inol: '0.075'
  volume: '24'
  week: 2
  weight: '87.6'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 3
  weight: '94.9'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6
  scheme: 9x2@70%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 4
  weight: '102.2'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 5
  weight: '109.5'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 6
  weight: '116.8'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.6
  scheme: 9x1@85%
  set_inol: '0.0666666666667'
  volume: '9'
  week: 7
  weight: '124.1'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 8
  weight: '131.4'
  weight_olympic: '131.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 9
  weight: '138.7'
  weight_olympic: '139.0'
  weight_powerlifting: '137.5'
