- exercise_inol: 0.6857142857142857
  scheme: 6x4@65%
  set_inol: '0.114285714286'
  volume: '24'
  week: 1
  weight: '44.2'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.7
  scheme: 3x7@70%
  set_inol: '0.233333333333'
  volume: '21'
  week: 2
  weight: '47.6'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  week: 3
  weight: '51.0'
  weight_olympic: '51.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.7
  scheme: 2x7@80%
  set_inol: '0.35'
  volume: '14'
  week: 4
  weight: '54.4'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  week: 5
  weight: '57.8'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '61.2'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '64.6'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
