- exercise_inol: 0.509090909090909
  scheme: 2x7@72.5%
  set_inol: '0.254545454545'
  volume: '14'
  week: 1
  weight: '49.3'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.5333333333333333
  scheme: 6x2@77.5%
  set_inol: '0.0888888888889'
  volume: '12'
  week: 2
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5142857142857142
  scheme: 3x3@82.5%
  set_inol: '0.171428571429'
  volume: '9'
  week: 3
  weight: '56.1'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.48
  scheme: 6x1@87.5%
  set_inol: '0.08'
  volume: '6'
  week: 4
  weight: '59.5'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 5
  weight: '62.9'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
