- exercise_inol: 0.3111111111111111
  scheme: 1x7@77.5%
  set_inol: '0.311111111111'
  volume: '7'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.35555555555555557
  scheme: 4x2@77.5%
  set_inol: '0.0888888888889'
  volume: '8'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.35555555555555557
  scheme: 2x4@77.5%
  set_inol: '0.177777777778'
  volume: '8'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.35555555555555557
  scheme: 1x8@77.5%
  set_inol: '0.355555555556'
  volume: '8'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 3x3@77.5%
  set_inol: '0.133333333333'
  volume: '9'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4444444444444444
  scheme: 2x5@77.5%
  set_inol: '0.222222222222'
  volume: '10'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4444444444444445
  scheme: 5x2@77.5%
  set_inol: '0.0888888888889'
  volume: '10'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5333333333333333
  scheme: 6x2@77.5%
  set_inol: '0.0888888888889'
  volume: '12'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x3@77.5%
  set_inol: '0.133333333333'
  volume: '12'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5333333333333333
  scheme: 3x4@77.5%
  set_inol: '0.177777777778'
  volume: '12'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5333333333333333
  scheme: 2x6@77.5%
  set_inol: '0.266666666667'
  volume: '12'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6222222222222222
  scheme: 2x7@77.5%
  set_inol: '0.311111111111'
  volume: '14'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x3@77.5%
  set_inol: '0.133333333333'
  volume: '15'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6666666666666666
  scheme: 3x5@77.5%
  set_inol: '0.222222222222'
  volume: '15'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.7111111111111111
  scheme: 4x4@77.5%
  set_inol: '0.177777777778'
  volume: '16'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.7111111111111111
  scheme: 2x8@77.5%
  set_inol: '0.355555555556'
  volume: '16'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 6x3@77.5%
  set_inol: '0.133333333333'
  volume: '18'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 3x6@77.5%
  set_inol: '0.266666666667'
  volume: '18'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8888888888888888
  scheme: 4x5@77.5%
  set_inol: '0.222222222222'
  volume: '20'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.888888888888889
  scheme: 5x4@77.5%
  set_inol: '0.177777777778'
  volume: '20'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.9333333333333333
  scheme: 3x7@77.5%
  set_inol: '0.311111111111'
  volume: '21'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0666666666666667
  scheme: 6x4@77.5%
  set_inol: '0.177777777778'
  volume: '24'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0666666666666667
  scheme: 4x6@77.5%
  set_inol: '0.266666666667'
  volume: '24'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0666666666666667
  scheme: 3x8@77.5%
  set_inol: '0.355555555556'
  volume: '24'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.1111111111111112
  scheme: 5x5@77.5%
  set_inol: '0.222222222222'
  volume: '25'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.2444444444444445
  scheme: 4x7@77.5%
  set_inol: '0.311111111111'
  volume: '28'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.3333333333333333
  scheme: 6x5@77.5%
  set_inol: '0.222222222222'
  volume: '30'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.3333333333333333
  scheme: 5x6@77.5%
  set_inol: '0.266666666667'
  volume: '30'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.4222222222222223
  scheme: 4x8@77.5%
  set_inol: '0.355555555556'
  volume: '32'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.5555555555555556
  scheme: 5x7@77.5%
  set_inol: '0.311111111111'
  volume: '35'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.6
  scheme: 6x6@77.5%
  set_inol: '0.266666666667'
  volume: '36'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.777777777777778
  scheme: 5x8@77.5%
  set_inol: '0.355555555556'
  volume: '40'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.8666666666666667
  scheme: 6x7@77.5%
  set_inol: '0.311111111111'
  volume: '42'
  weight: '52.7'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
