- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '45.5'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '49.0'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '52.5'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '56.0'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '59.5'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '63.0'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '66.5'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
