- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '44.2'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '47.6'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '51.0'
  weight_olympic: '51.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '54.4'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '57.8'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '61.2'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '64.6'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
