- exercise_inol: 0.6
  scheme: 4x6@60%
  set_inol: '0.15'
  volume: '24'
  week: 1
  weight: '36.6'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 2
  weight: '39.65'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 3
  weight: '42.7'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 4
  weight: '45.75'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 5
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 6
  weight: '51.85'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 7
  weight: '54.9'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 8
  weight: '57.95'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
