- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '120.25'
  weight_olympic: '120.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '129.5'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '138.75'
  weight_olympic: '139.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '148.0'
  weight_olympic: '148.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '157.25'
  weight_olympic: '157.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '166.5'
  weight_olympic: '167.0'
  weight_powerlifting: '167.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '175.75'
  weight_olympic: '176.0'
  weight_powerlifting: '175.0'
