- exercise_inol: 0.4
  scheme: 2x7@65%
  set_inol: '0.2'
  volume: '14'
  week: 1
  weight: '71.5'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 2
  weight: '77.0'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '88.0'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 5
  weight: '93.5'
  weight_olympic: '94.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '99.0'
  weight_olympic: '99.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '104.5'
  weight_olympic: '105.0'
  weight_powerlifting: '105.0'
