- exercise_inol: 0.39999999999999997
  scheme: 7x2@65%
  set_inol: '0.0571428571429'
  volume: '14'
  week: 1
  weight: '43.55'
  weight_olympic: '44.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 2
  weight: '46.9'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '50.25'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 5
  weight: '56.95'
  weight_olympic: '57.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '60.3'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '63.65'
  weight_olympic: '64.0'
  weight_powerlifting: '62.5'
