- exercise_inol: 0.32
  scheme: 4x1@87.5%
  set_inol: '0.08'
  volume: '4'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.32
  scheme: 2x2@87.5%
  set_inol: '0.16'
  volume: '4'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 5x1@87.5%
  set_inol: '0.08'
  volume: '5'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.48
  scheme: 6x1@87.5%
  set_inol: '0.08'
  volume: '6'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.48
  scheme: 3x2@87.5%
  set_inol: '0.16'
  volume: '6'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.48
  scheme: 2x3@87.5%
  set_inol: '0.24'
  volume: '6'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.56
  scheme: 7x1@87.5%
  set_inol: '0.08'
  volume: '7'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.64
  scheme: 8x1@87.5%
  set_inol: '0.08'
  volume: '8'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.64
  scheme: 4x2@87.5%
  set_inol: '0.16'
  volume: '8'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.72
  scheme: 9x1@87.5%
  set_inol: '0.08'
  volume: '9'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.72
  scheme: 3x3@87.5%
  set_inol: '0.24'
  volume: '9'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 10x1@87.5%
  set_inol: '0.08'
  volume: '10'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 5x2@87.5%
  set_inol: '0.16'
  volume: '10'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.96
  scheme: 6x2@87.5%
  set_inol: '0.16'
  volume: '12'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.96
  scheme: 4x3@87.5%
  set_inol: '0.24'
  volume: '12'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.12
  scheme: 7x2@87.5%
  set_inol: '0.16'
  volume: '14'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.2
  scheme: 5x3@87.5%
  set_inol: '0.24'
  volume: '15'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.28
  scheme: 8x2@87.5%
  set_inol: '0.16'
  volume: '16'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.44
  scheme: 9x2@87.5%
  set_inol: '0.16'
  volume: '18'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.44
  scheme: 6x3@87.5%
  set_inol: '0.24'
  volume: '18'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.6
  scheme: 10x2@87.5%
  set_inol: '0.16'
  volume: '20'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.68
  scheme: 7x3@87.5%
  set_inol: '0.24'
  volume: '21'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.92
  scheme: 8x3@87.5%
  set_inol: '0.24'
  volume: '24'
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
