- exercise_inol: 0.30000000000000004
  scheme: 3x2@80%
  set_inol: '0.1'
  volume: '6'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.7000000000000001
  scheme: 7x2@80%
  set_inol: '0.1'
  volume: '14'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.9
  scheme: 9x2@80%
  set_inol: '0.1'
  volume: '18'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0
  scheme: 10x2@80%
  set_inol: '0.1'
  volume: '20'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.05
  scheme: 7x3@80%
  set_inol: '0.15'
  volume: '21'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.2
  scheme: 8x3@80%
  set_inol: '0.15'
  volume: '24'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.3499999999999999
  scheme: 9x3@80%
  set_inol: '0.15'
  volume: '27'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.5
  scheme: 10x3@80%
  set_inol: '0.15'
  volume: '30'
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
