- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '113.75'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '122.5'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '131.25'
  weight_olympic: '131.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '140.0'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '148.75'
  weight_olympic: '149.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '157.5'
  weight_olympic: '158.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '166.25'
  weight_olympic: '166.0'
  weight_powerlifting: '167.5'
