- exercise_inol: 0.6000000000000001
  scheme: 3x9@55%
  set_inol: '0.2'
  volume: '27'
  week: 1
  weight: '104.5'
  weight_olympic: '105.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.6
  scheme: 4x6@60%
  set_inol: '0.15'
  volume: '24'
  week: 2
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 3
  weight: '123.5'
  weight_olympic: '124.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 4
  weight: '133.0'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 5
  weight: '142.5'
  weight_olympic: '143.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 6
  weight: '152.0'
  weight_olympic: '152.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 7
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 8
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 9
  weight: '180.5'
  weight_olympic: '181.0'
  weight_powerlifting: '180.0'
