- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '125.45'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '135.1'
  weight_olympic: '135.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.8
  scheme: 4x5@75%
  set_inol: '0.2'
  volume: '20'
  week: 3
  weight: '144.75'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '154.4'
  weight_olympic: '154.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '164.05'
  weight_olympic: '164.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '173.7'
  weight_olympic: '174.0'
  weight_powerlifting: '172.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '183.35'
  weight_olympic: '183.0'
  weight_powerlifting: '182.5'
