- exercise_inol: 0.5142857142857142
  scheme: 2x9@65%
  set_inol: '0.257142857143'
  volume: '18'
  week: 1
  weight: '124.8'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.5
  scheme: 3x5@70%
  set_inol: '0.166666666667'
  volume: '15'
  week: 2
  weight: '134.4'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.48
  scheme: 2x6@75%
  set_inol: '0.24'
  volume: '12'
  week: 3
  weight: '144.0'
  weight_olympic: '144.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.5
  scheme: 2x5@80%
  set_inol: '0.25'
  volume: '10'
  week: 4
  weight: '153.6'
  weight_olympic: '154.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.5333333333333333
  scheme: 2x4@85%
  set_inol: '0.266666666667'
  volume: '8'
  week: 5
  weight: '163.2'
  weight_olympic: '163.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '172.8'
  weight_olympic: '173.0'
  weight_powerlifting: '172.5'
