- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 1
  weight: '136.5'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 2
  weight: '146.25'
  weight_olympic: '146.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 3
  weight: '156.0'
  weight_olympic: '156.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 4
  weight: '165.75'
  weight_olympic: '166.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 5
  weight: '175.5'
  weight_olympic: '176.0'
  weight_powerlifting: '175.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 6
  weight: '185.25'
  weight_olympic: '185.0'
  weight_powerlifting: '185.0'
