- exercise_inol: 0.30000000000000004
  scheme: 3x4@60%
  set_inol: '0.1'
  volume: '12'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.35
  scheme: 2x7@60%
  set_inol: '0.175'
  volume: '14'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.375
  scheme: 5x3@60%
  set_inol: '0.075'
  volume: '15'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.375
  scheme: 3x5@60%
  set_inol: '0.125'
  volume: '15'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.4
  scheme: 2x8@60%
  set_inol: '0.2'
  volume: '16'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.44999999999999996
  scheme: 3x6@60%
  set_inol: '0.15'
  volume: '18'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.45
  scheme: 2x9@60%
  set_inol: '0.225'
  volume: '18'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.5
  scheme: 5x4@60%
  set_inol: '0.1'
  volume: '20'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.5
  scheme: 4x5@60%
  set_inol: '0.125'
  volume: '20'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.5
  scheme: 2x10@60%
  set_inol: '0.25'
  volume: '20'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.5249999999999999
  scheme: 3x7@60%
  set_inol: '0.175'
  volume: '21'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.55
  scheme: 2x11@60%
  set_inol: '0.275'
  volume: '22'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6
  scheme: 4x6@60%
  set_inol: '0.15'
  volume: '24'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6
  scheme: 2x12@60%
  set_inol: '0.3'
  volume: '24'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x8@60%
  set_inol: '0.2'
  volume: '24'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.625
  scheme: 5x5@60%
  set_inol: '0.125'
  volume: '25'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.675
  scheme: 3x9@60%
  set_inol: '0.225'
  volume: '27'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.7
  scheme: 4x7@60%
  set_inol: '0.175'
  volume: '28'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.75
  scheme: 5x6@60%
  set_inol: '0.15'
  volume: '30'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.75
  scheme: 3x10@60%
  set_inol: '0.25'
  volume: '30'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.8
  scheme: 4x8@60%
  set_inol: '0.2'
  volume: '32'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.8250000000000001
  scheme: 3x11@60%
  set_inol: '0.275'
  volume: '33'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.875
  scheme: 5x7@60%
  set_inol: '0.175'
  volume: '35'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x12@60%
  set_inol: '0.3'
  volume: '36'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.9
  scheme: 4x9@60%
  set_inol: '0.225'
  volume: '36'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.0
  scheme: 5x8@60%
  set_inol: '0.2'
  volume: '40'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.0
  scheme: 4x10@60%
  set_inol: '0.25'
  volume: '40'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.1
  scheme: 4x11@60%
  set_inol: '0.275'
  volume: '44'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.125
  scheme: 5x9@60%
  set_inol: '0.225'
  volume: '45'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.2
  scheme: 4x12@60%
  set_inol: '0.3'
  volume: '48'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.25
  scheme: 5x10@60%
  set_inol: '0.25'
  volume: '50'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.375
  scheme: 5x11@60%
  set_inol: '0.275'
  volume: '55'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.5
  scheme: 5x12@60%
  set_inol: '0.3'
  volume: '60'
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
