- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '125.125'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '134.75'
  weight_olympic: '135.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '144.375'
  weight_olympic: '144.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '154.0'
  weight_olympic: '154.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '163.625'
  weight_olympic: '164.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '173.25'
  weight_olympic: '173.0'
  weight_powerlifting: '172.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '182.875'
  weight_olympic: '183.0'
  weight_powerlifting: '182.5'
