- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 1
  weight: '133.7'
  weight_olympic: '134.0'
  weight_powerlifting: '132.5'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 2
  weight: '143.25'
  weight_olympic: '143.0'
  weight_powerlifting: '142.5'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 3
  weight: '152.8'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 4
  weight: '162.35'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 5
  weight: '171.9'
  weight_olympic: '172.0'
  weight_powerlifting: '172.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 6
  weight: '181.45'
  weight_olympic: '181.0'
  weight_powerlifting: '182.5'
