- exercise_inol: 0.7714285714285714
  scheme: 3x9@65%
  set_inol: '0.257142857143'
  volume: '27'
  week: 1
  weight: '126.1'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '135.8'
  weight_olympic: '136.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.72
  scheme: 3x6@75%
  set_inol: '0.24'
  volume: '18'
  week: 3
  weight: '145.5'
  weight_olympic: '146.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.75
  scheme: 3x5@80%
  set_inol: '0.25'
  volume: '15'
  week: 4
  weight: '155.2'
  weight_olympic: '155.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '164.9'
  weight_olympic: '165.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '174.6'
  weight_olympic: '175.0'
  weight_powerlifting: '175.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '184.3'
  weight_olympic: '184.0'
  weight_powerlifting: '185.0'
