- exercise_inol: 0.3111111111111111
  scheme: 2x7@55%
  set_inol: '0.155555555556'
  volume: '14'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.3333333333333333
  scheme: 3x5@55%
  set_inol: '0.111111111111'
  volume: '15'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.35555555555555557
  scheme: 4x4@55%
  set_inol: '0.0888888888889'
  volume: '16'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.35555555555555557
  scheme: 2x8@55%
  set_inol: '0.177777777778'
  volume: '16'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4
  scheme: 3x6@55%
  set_inol: '0.133333333333'
  volume: '18'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4
  scheme: 2x9@55%
  set_inol: '0.2'
  volume: '18'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4444444444444444
  scheme: 4x5@55%
  set_inol: '0.111111111111'
  volume: '20'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4444444444444444
  scheme: 2x10@55%
  set_inol: '0.222222222222'
  volume: '20'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4666666666666667
  scheme: 3x7@55%
  set_inol: '0.155555555556'
  volume: '21'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x6@55%
  set_inol: '0.133333333333'
  volume: '24'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.5333333333333333
  scheme: 3x8@55%
  set_inol: '0.177777777778'
  volume: '24'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x9@55%
  set_inol: '0.2'
  volume: '27'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6222222222222222
  scheme: 4x7@55%
  set_inol: '0.155555555556'
  volume: '28'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6666666666666666
  scheme: 3x10@55%
  set_inol: '0.222222222222'
  volume: '30'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.7111111111111111
  scheme: 4x8@55%
  set_inol: '0.177777777778'
  volume: '32'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x9@55%
  set_inol: '0.2'
  volume: '36'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8888888888888888
  scheme: 4x10@55%
  set_inol: '0.222222222222'
  volume: '40'
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
