- exercise_inol: 0.6285714285714286
  scheme: 2x11@65%
  set_inol: '0.314285714286'
  volume: '22'
  week: 1
  weight: '74.75'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x4@70%
  set_inol: '0.133333333333'
  volume: '20'
  week: 2
  weight: '80.5'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.64
  scheme: 4x4@75%
  set_inol: '0.16'
  volume: '16'
  week: 3
  weight: '86.25'
  weight_olympic: '86.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  week: 4
  weight: '92.0'
  weight_olympic: '92.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  week: 5
  weight: '97.75'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '103.5'
  weight_olympic: '104.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '109.25'
  weight_olympic: '109.0'
  weight_powerlifting: '110.0'
