- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.0
  scheme: 6x5@70%
  set_inol: '0.166666666667'
  volume: '30'
  week: 2
  weight: '84.0'
  weight_olympic: '84.0'
  weight_powerlifting: '85.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '96.0'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '102.0'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '108.0'
  weight_olympic: '108.0'
  weight_powerlifting: '107.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
