- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '119.0'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '127.5'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '136.0'
  weight_olympic: '136.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '144.5'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '153.0'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
