- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '94.25'
  weight_olympic: '94.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '101.5'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '108.75'
  weight_olympic: '109.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '116.0'
  weight_olympic: '116.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '123.25'
  weight_olympic: '123.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '130.5'
  weight_olympic: '131.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '137.75'
  weight_olympic: '138.0'
  weight_powerlifting: '137.5'
