- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '65.65'
  weight_olympic: '66.0'
  weight_powerlifting: '65.0'
- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '70.7'
  weight_olympic: '71.0'
  weight_powerlifting: '70.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '75.75'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '80.8'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '85.85'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '90.9'
  weight_olympic: '91.0'
  weight_powerlifting: '90.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '95.95'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
