- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '63.05'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '67.9'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '72.75'
  weight_olympic: '73.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '77.6'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '82.45'
  weight_olympic: '82.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '87.3'
  weight_olympic: '87.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '92.15'
  weight_olympic: '92.0'
  weight_powerlifting: '92.5'
