- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '60.125'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '64.75'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '69.375'
  weight_olympic: '69.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '74.0'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '78.625'
  weight_olympic: '79.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '83.25'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '87.875'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
