- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 1
  weight: '85.4'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 2
  weight: '91.5'
  weight_olympic: '92.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 3
  weight: '97.6'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 4
  weight: '103.7'
  weight_olympic: '104.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 5
  weight: '109.8'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 6
  weight: '115.9'
  weight_olympic: '116.0'
  weight_powerlifting: '115.0'
