- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '50.05'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '53.9'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '57.75'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '61.6'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '65.45'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '69.3'
  weight_olympic: '69.0'
  weight_powerlifting: '70.0'
