- exercise_inol: 0.8
  scheme: 9x4@55%
  set_inol: '0.0888888888889'
  volume: '36'
  week: 1
  weight: '68.75'
  weight_olympic: '69.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.8
  scheme: 8x4@60%
  set_inol: '0.1'
  volume: '32'
  week: 2
  weight: '75.0'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 3
  weight: '81.25'
  weight_olympic: '81.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 4
  weight: '87.5'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 5
  weight: '93.75'
  weight_olympic: '94.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 6
  weight: '100.0'
  weight_olympic: '100.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 7
  weight: '106.25'
  weight_olympic: '106.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 8
  weight: '112.5'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 9
  weight: '118.75'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
