- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 1
  weight: '55.25'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '59.5'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '63.75'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '68.0'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '72.25'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '76.5'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '80.75'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
