- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '140.0'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '150.0'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '160.0'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '170.0'
  weight_olympic: '170.0'
  weight_powerlifting: '170.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '180.0'
  weight_olympic: '180.0'
  weight_powerlifting: '180.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '190.0'
  weight_olympic: '190.0'
  weight_powerlifting: '190.0'
