- exercise_inol: 0.39999999999999997
  scheme: 7x2@65%
  set_inol: '0.0571428571429'
  volume: '14'
  week: 1
  weight: '42.9'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 2
  weight: '46.2'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '49.5'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 5
  weight: '56.1'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '59.4'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '62.7'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
