- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  weight: '77.9'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  weight: '77.9'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  weight: '77.9'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  weight: '77.9'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
