- exercise_inol: 0.5142857142857142
  scheme: 3x6@65%
  set_inol: '0.171428571429'
  volume: '18'
  week: 1
  weight: '54.6'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5
  scheme: 5x3@70%
  set_inol: '0.1'
  volume: '15'
  week: 2
  weight: '58.8'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  week: 3
  weight: '63.0'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  week: 4
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85%
  set_inol: '0.133333333333'
  volume: '8'
  week: 5
  weight: '71.4'
  weight_olympic: '71.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.5
  scheme: 5x1@90%
  set_inol: '0.1'
  volume: '5'
  week: 6
  weight: '75.6'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '79.8'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
