- exercise_inol: 0.43636363636363634
  scheme: 4x3@72.5%
  set_inol: '0.109090909091'
  volume: '12'
  week: 1
  weight: '50.75'
  weight_olympic: '51.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 3x3@77.5%
  set_inol: '0.133333333333'
  volume: '9'
  week: 2
  weight: '54.25'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.45714285714285713
  scheme: 4x2@82.5%
  set_inol: '0.114285714286'
  volume: '8'
  week: 3
  weight: '57.75'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.4
  scheme: 5x1@87.5%
  set_inol: '0.08'
  volume: '5'
  week: 4
  weight: '61.25'
  weight_olympic: '61.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.4
  scheme: 3x1@92.5%
  set_inol: '0.133333333333'
  volume: '3'
  week: 5
  weight: '64.75'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
