- exercise_inol: 0.30000000000000004
  scheme: 3x2@80%
  set_inol: '0.1'
  volume: '6'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.4
  scheme: 2x4@80%
  set_inol: '0.2'
  volume: '8'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.5
  scheme: 2x5@80%
  set_inol: '0.25'
  volume: '10'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6
  scheme: 2x6@80%
  set_inol: '0.3'
  volume: '12'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x4@80%
  set_inol: '0.2'
  volume: '12'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.75
  scheme: 3x5@80%
  set_inol: '0.25'
  volume: '15'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x6@80%
  set_inol: '0.3'
  volume: '18'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 1.0
  scheme: 4x5@80%
  set_inol: '0.25'
  volume: '20'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 1.2
  scheme: 4x6@80%
  set_inol: '0.3'
  volume: '24'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 1.25
  scheme: 5x5@80%
  set_inol: '0.25'
  volume: '25'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 1.5
  scheme: 5x6@80%
  set_inol: '0.3'
  volume: '30'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
