- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '74.75'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '80.5'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '86.25'
  weight_olympic: '86.0'
  weight_powerlifting: '87.5'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '92.0'
  weight_olympic: '92.0'
  weight_powerlifting: '92.5'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '97.75'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '103.5'
  weight_olympic: '104.0'
  weight_powerlifting: '102.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '109.25'
  weight_olympic: '109.0'
  weight_powerlifting: '110.0'
