- exercise_inol: 0.6
  scheme: 4x6@60%
  set_inol: '0.15'
  volume: '24'
  week: 1
  weight: '70.5'
  weight_olympic: '71.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 2
  weight: '76.375'
  weight_olympic: '76.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 3
  weight: '82.25'
  weight_olympic: '82.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 4
  weight: '88.125'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.6
  scheme: 2x6@80%
  set_inol: '0.3'
  volume: '12'
  week: 5
  weight: '94.0'
  weight_olympic: '94.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 6
  weight: '99.875'
  weight_olympic: '100.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 7
  weight: '105.75'
  weight_olympic: '106.0'
  weight_powerlifting: '105.0'
