- exercise_inol: 0.7714285714285714
  scheme: 3x9@65%
  set_inol: '0.257142857143'
  volume: '27'
  week: 1
  weight: '76.375'
  weight_olympic: '76.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '82.25'
  weight_olympic: '82.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.72
  scheme: 3x6@75%
  set_inol: '0.24'
  volume: '18'
  week: 3
  weight: '88.125'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  week: 4
  weight: '94.0'
  weight_olympic: '94.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '99.875'
  weight_olympic: '100.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '105.75'
  weight_olympic: '106.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '111.625'
  weight_olympic: '112.0'
  weight_powerlifting: '112.5'
