- exercise_inol: 0.8571428571428571
  scheme: 3x10@65%
  set_inol: '0.285714285714'
  volume: '30'
  week: 1
  weight: '79.625'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8333333333333333
  scheme: 5x5@70%
  set_inol: '0.166666666667'
  volume: '25'
  week: 2
  weight: '85.75'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8400000000000001
  scheme: 3x7@75%
  set_inol: '0.28'
  volume: '21'
  week: 3
  weight: '91.875'
  weight_olympic: '92.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '98.0'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '104.125'
  weight_olympic: '104.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '110.25'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '116.375'
  weight_olympic: '116.0'
  weight_powerlifting: '117.5'
