- exercise_inol: 1.0285714285714285
  scheme: 6x6@65%
  set_inol: '0.171428571429'
  volume: '36'
  week: 1
  weight: '32.5'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 1.0666666666666667
  scheme: 4x8@70%
  set_inol: '0.266666666667'
  volume: '32'
  week: 2
  weight: '35.0'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.08
  scheme: 3x9@75%
  set_inol: '0.36'
  volume: '27'
  week: 3
  weight: '37.5'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 1.0499999999999998
  scheme: 3x7@80%
  set_inol: '0.35'
  volume: '21'
  week: 4
  weight: '40.0'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.0666666666666667
  scheme: 4x4@85%
  set_inol: '0.266666666667'
  volume: '16'
  week: 5
  weight: '42.5'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '45.0'
  weight_olympic: '45.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '47.5'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
