- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '32.5'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 1.0
  scheme: 6x5@70%
  set_inol: '0.166666666667'
  volume: '30'
  week: 2
  weight: '35.0'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '37.5'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '40.0'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '42.5'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '45.0'
  weight_olympic: '45.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '47.5'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
