- exercise_inol: 0.4
  scheme: 6x3@55%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 1
  weight: '81.4'
  weight_olympic: '81.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  week: 2
  weight: '88.8'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.42857142857142855
  scheme: 3x5@65%
  set_inol: '0.142857142857'
  volume: '15'
  week: 3
  weight: '96.2'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 4
  weight: '103.6'
  weight_olympic: '104.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 5
  weight: '111.0'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '118.4'
  weight_olympic: '118.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 7
  weight: '125.8'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 8
  weight: '133.2'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 9
  weight: '140.6'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
