- exercise_inol: 0.36363636363636365
  scheme: 4x3@67%
  set_inol: '0.0909090909091'
  volume: '12'
  week: 1
  weight: '70.35'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.42857142857142855
  scheme: 4x3@72%
  set_inol: '0.107142857143'
  volume: '12'
  week: 2
  weight: '75.6'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.3913043478260869
  scheme: 3x3@77%
  set_inol: '0.130434782609'
  volume: '9'
  week: 3
  weight: '80.85'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.4444444444444444
  scheme: 4x2@82%
  set_inol: '0.111111111111'
  volume: '8'
  week: 4
  weight: '86.1'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.38461538461538464
  scheme: 5x1@87%
  set_inol: '0.0769230769231'
  volume: '5'
  week: 5
  weight: '91.35'
  weight_olympic: '91.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.375
  scheme: 3x1@92%
  set_inol: '0.125'
  volume: '3'
  week: 6
  weight: '96.6'
  weight_olympic: '97.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.3333333333333333
  scheme: 1x1@97%
  set_inol: '0.333333333333'
  volume: '1'
  week: 7
  weight: '101.85'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
