- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '39.65'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '42.7'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '45.75'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '51.85'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '54.9'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '57.95'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
