- exercise_inol: 0.3333333333333333
  scheme: 4x1@88%
  set_inol: '0.0833333333333'
  volume: '4'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.3333333333333333
  scheme: 2x2@88%
  set_inol: '0.166666666667'
  volume: '4'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.3333333333333333
  scheme: 1x4@88%
  set_inol: '0.333333333333'
  volume: '4'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.41666666666666663
  scheme: 5x1@88%
  set_inol: '0.0833333333333'
  volume: '5'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5
  scheme: 6x1@88%
  set_inol: '0.0833333333333'
  volume: '6'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5
  scheme: 3x2@88%
  set_inol: '0.166666666667'
  volume: '6'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5
  scheme: 2x3@88%
  set_inol: '0.25'
  volume: '6'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5833333333333333
  scheme: 7x1@88%
  set_inol: '0.0833333333333'
  volume: '7'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6666666666666666
  scheme: 8x1@88%
  set_inol: '0.0833333333333'
  volume: '8'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6666666666666666
  scheme: 4x2@88%
  set_inol: '0.166666666667'
  volume: '8'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6666666666666666
  scheme: 2x4@88%
  set_inol: '0.333333333333'
  volume: '8'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.75
  scheme: 9x1@88%
  set_inol: '0.0833333333333'
  volume: '9'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.75
  scheme: 3x3@88%
  set_inol: '0.25'
  volume: '9'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8333333333333333
  scheme: 10x1@88%
  set_inol: '0.0833333333333'
  volume: '10'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8333333333333333
  scheme: 5x2@88%
  set_inol: '0.166666666667'
  volume: '10'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0
  scheme: 6x2@88%
  set_inol: '0.166666666667'
  volume: '12'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0
  scheme: 4x3@88%
  set_inol: '0.25'
  volume: '12'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0
  scheme: 3x4@88%
  set_inol: '0.333333333333'
  volume: '12'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.1666666666666665
  scheme: 7x2@88%
  set_inol: '0.166666666667'
  volume: '14'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.25
  scheme: 5x3@88%
  set_inol: '0.25'
  volume: '15'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.3333333333333333
  scheme: 8x2@88%
  set_inol: '0.166666666667'
  volume: '16'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.3333333333333333
  scheme: 4x4@88%
  set_inol: '0.333333333333'
  volume: '16'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.5
  scheme: 9x2@88%
  set_inol: '0.166666666667'
  volume: '18'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.5
  scheme: 6x3@88%
  set_inol: '0.25'
  volume: '18'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.6666666666666665
  scheme: 10x2@88%
  set_inol: '0.166666666667'
  volume: '20'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.6666666666666665
  scheme: 5x4@88%
  set_inol: '0.333333333333'
  volume: '20'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.75
  scheme: 7x3@88%
  set_inol: '0.25'
  volume: '21'
  weight: '52.8'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
