- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '43.55'
  weight_olympic: '44.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '46.9'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '50.25'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '53.6'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '56.95'
  weight_olympic: '57.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '60.3'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '63.65'
  weight_olympic: '64.0'
  weight_powerlifting: '62.5'
