- exercise_inol: 0.9696969696969697
  scheme: 8x4@67%
  set_inol: '0.121212121212'
  volume: '32'
  week: 1
  weight: '40.2'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 1.0
  scheme: 7x4@72%
  set_inol: '0.142857142857'
  volume: '28'
  week: 2
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0434782608695652
  scheme: 8x3@77%
  set_inol: '0.130434782609'
  volume: '24'
  week: 3
  weight: '46.2'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.0
  scheme: 9x2@82%
  set_inol: '0.111111111111'
  volume: '18'
  week: 4
  weight: '49.2'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.9230769230769231
  scheme: 6x2@87%
  set_inol: '0.153846153846'
  volume: '12'
  week: 5
  weight: '52.2'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0
  scheme: 8x1@92%
  set_inol: '0.125'
  volume: '8'
  week: 6
  weight: '55.2'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0
  scheme: 3x1@97%
  set_inol: '0.333333333333'
  volume: '3'
  week: 7
  weight: '58.2'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
