- exercise_inol: 0.30000000000000004
  scheme: 3x2@80%
  set_inol: '0.1'
  volume: '6'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 2x4@80%
  set_inol: '0.2'
  volume: '8'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.5
  scheme: 2x5@80%
  set_inol: '0.25'
  volume: '10'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x4@80%
  set_inol: '0.2'
  volume: '12'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.7000000000000001
  scheme: 7x2@80%
  set_inol: '0.1'
  volume: '14'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.75
  scheme: 3x5@80%
  set_inol: '0.25'
  volume: '15'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.9
  scheme: 9x2@80%
  set_inol: '0.1'
  volume: '18'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.0
  scheme: 10x2@80%
  set_inol: '0.1'
  volume: '20'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.0
  scheme: 4x5@80%
  set_inol: '0.25'
  volume: '20'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.05
  scheme: 7x3@80%
  set_inol: '0.15'
  volume: '21'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.2
  scheme: 8x3@80%
  set_inol: '0.15'
  volume: '24'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x4@80%
  set_inol: '0.2'
  volume: '24'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.25
  scheme: 5x5@80%
  set_inol: '0.25'
  volume: '25'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.3499999999999999
  scheme: 9x3@80%
  set_inol: '0.15'
  volume: '27'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.4000000000000001
  scheme: 7x4@80%
  set_inol: '0.2'
  volume: '28'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.5
  scheme: 10x3@80%
  set_inol: '0.15'
  volume: '30'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.5
  scheme: 6x5@80%
  set_inol: '0.25'
  volume: '30'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.6
  scheme: 8x4@80%
  set_inol: '0.2'
  volume: '32'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.75
  scheme: 7x5@80%
  set_inol: '0.25'
  volume: '35'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.8
  scheme: 9x4@80%
  set_inol: '0.2'
  volume: '36'
  weight: '48.8'
  weight_olympic: '49.0'
  weight_powerlifting: '50.0'
