- exercise_inol: 0.3214285714285714
  scheme: 3x3@72%
  set_inol: '0.107142857143'
  volume: '9'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.3571428571428571
  scheme: 5x2@72%
  set_inol: '0.0714285714286'
  volume: '10'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.35714285714285715
  scheme: 2x5@72%
  set_inol: '0.178571428571'
  volume: '10'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.42857142857142855
  scheme: 6x2@72%
  set_inol: '0.0714285714286'
  volume: '12'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.42857142857142855
  scheme: 4x3@72%
  set_inol: '0.107142857143'
  volume: '12'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.42857142857142855
  scheme: 3x4@72%
  set_inol: '0.142857142857'
  volume: '12'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5
  scheme: 7x2@72%
  set_inol: '0.0714285714286'
  volume: '14'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5357142857142857
  scheme: 5x3@72%
  set_inol: '0.107142857143'
  volume: '15'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5357142857142857
  scheme: 3x5@72%
  set_inol: '0.178571428571'
  volume: '15'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5714285714285714
  scheme: 8x2@72%
  set_inol: '0.0714285714286'
  volume: '16'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5714285714285714
  scheme: 4x4@72%
  set_inol: '0.142857142857'
  volume: '16'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6428571428571428
  scheme: 9x2@72%
  set_inol: '0.0714285714286'
  volume: '18'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6428571428571428
  scheme: 6x3@72%
  set_inol: '0.107142857143'
  volume: '18'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.7142857142857142
  scheme: 10x2@72%
  set_inol: '0.0714285714286'
  volume: '20'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.7142857142857142
  scheme: 5x4@72%
  set_inol: '0.142857142857'
  volume: '20'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.7142857142857143
  scheme: 4x5@72%
  set_inol: '0.178571428571'
  volume: '20'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.75
  scheme: 7x3@72%
  set_inol: '0.107142857143'
  volume: '21'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8571428571428571
  scheme: 8x3@72%
  set_inol: '0.107142857143'
  volume: '24'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8571428571428571
  scheme: 6x4@72%
  set_inol: '0.142857142857'
  volume: '24'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8928571428571429
  scheme: 5x5@72%
  set_inol: '0.178571428571'
  volume: '25'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.9642857142857142
  scheme: 9x3@72%
  set_inol: '0.107142857143'
  volume: '27'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0
  scheme: 7x4@72%
  set_inol: '0.142857142857'
  volume: '28'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0714285714285714
  scheme: 10x3@72%
  set_inol: '0.107142857143'
  volume: '30'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0714285714285714
  scheme: 6x5@72%
  set_inol: '0.178571428571'
  volume: '30'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.1428571428571428
  scheme: 8x4@72%
  set_inol: '0.142857142857'
  volume: '32'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.25
  scheme: 7x5@72%
  set_inol: '0.178571428571'
  volume: '35'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.2857142857142856
  scheme: 9x4@72%
  set_inol: '0.142857142857'
  volume: '36'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.4285714285714284
  scheme: 10x4@72%
  set_inol: '0.142857142857'
  volume: '40'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.4285714285714286
  scheme: 8x5@72%
  set_inol: '0.178571428571'
  volume: '40'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.6071428571428572
  scheme: 9x5@72%
  set_inol: '0.178571428571'
  volume: '45'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.7857142857142858
  scheme: 10x5@72%
  set_inol: '0.178571428571'
  volume: '50'
  weight: '43.2'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
