- exercise_inol: 0.3571428571428571
  scheme: 5x1@86%
  set_inol: '0.0714285714286'
  volume: '5'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.35714285714285715
  scheme: 1x5@86%
  set_inol: '0.357142857143'
  volume: '5'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.42857142857142855
  scheme: 6x1@86%
  set_inol: '0.0714285714286'
  volume: '6'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.42857142857142855
  scheme: 3x2@86%
  set_inol: '0.142857142857'
  volume: '6'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.42857142857142855
  scheme: 2x3@86%
  set_inol: '0.214285714286'
  volume: '6'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5
  scheme: 7x1@86%
  set_inol: '0.0714285714286'
  volume: '7'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5714285714285714
  scheme: 8x1@86%
  set_inol: '0.0714285714286'
  volume: '8'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5714285714285714
  scheme: 4x2@86%
  set_inol: '0.142857142857'
  volume: '8'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5714285714285714
  scheme: 2x4@86%
  set_inol: '0.285714285714'
  volume: '8'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6428571428571428
  scheme: 9x1@86%
  set_inol: '0.0714285714286'
  volume: '9'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6428571428571428
  scheme: 3x3@86%
  set_inol: '0.214285714286'
  volume: '9'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.7142857142857142
  scheme: 10x1@86%
  set_inol: '0.0714285714286'
  volume: '10'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.7142857142857142
  scheme: 5x2@86%
  set_inol: '0.142857142857'
  volume: '10'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.7142857142857143
  scheme: 2x5@86%
  set_inol: '0.357142857143'
  volume: '10'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8571428571428571
  scheme: 6x2@86%
  set_inol: '0.142857142857'
  volume: '12'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8571428571428571
  scheme: 4x3@86%
  set_inol: '0.214285714286'
  volume: '12'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8571428571428571
  scheme: 3x4@86%
  set_inol: '0.285714285714'
  volume: '12'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0
  scheme: 7x2@86%
  set_inol: '0.142857142857'
  volume: '14'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0714285714285714
  scheme: 5x3@86%
  set_inol: '0.214285714286'
  volume: '15'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.0714285714285714
  scheme: 3x5@86%
  set_inol: '0.357142857143'
  volume: '15'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.1428571428571428
  scheme: 8x2@86%
  set_inol: '0.142857142857'
  volume: '16'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.1428571428571428
  scheme: 4x4@86%
  set_inol: '0.285714285714'
  volume: '16'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.2857142857142856
  scheme: 9x2@86%
  set_inol: '0.142857142857'
  volume: '18'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.2857142857142856
  scheme: 6x3@86%
  set_inol: '0.214285714286'
  volume: '18'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.4285714285714284
  scheme: 10x2@86%
  set_inol: '0.142857142857'
  volume: '20'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.4285714285714284
  scheme: 5x4@86%
  set_inol: '0.285714285714'
  volume: '20'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.4285714285714286
  scheme: 4x5@86%
  set_inol: '0.357142857143'
  volume: '20'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.5
  scheme: 7x3@86%
  set_inol: '0.214285714286'
  volume: '21'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.7142857142857142
  scheme: 8x3@86%
  set_inol: '0.214285714286'
  volume: '24'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.7142857142857142
  scheme: 6x4@86%
  set_inol: '0.285714285714'
  volume: '24'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.7857142857142858
  scheme: 5x5@86%
  set_inol: '0.357142857143'
  volume: '25'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 1.9285714285714284
  scheme: 9x3@86%
  set_inol: '0.214285714286'
  volume: '27'
  weight: '51.6'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
