- exercise_inol: 0.32
  scheme: 4x2@75%
  set_inol: '0.08'
  volume: '8'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.32
  scheme: 2x4@75%
  set_inol: '0.16'
  volume: '8'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.36
  scheme: 3x3@75%
  set_inol: '0.12'
  volume: '9'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4
  scheme: 2x5@75%
  set_inol: '0.2'
  volume: '10'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.48
  scheme: 6x2@75%
  set_inol: '0.08'
  volume: '12'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.48
  scheme: 3x4@75%
  set_inol: '0.16'
  volume: '12'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.56
  scheme: 7x2@75%
  set_inol: '0.08'
  volume: '14'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x5@75%
  set_inol: '0.2'
  volume: '15'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.64
  scheme: 8x2@75%
  set_inol: '0.08'
  volume: '16'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.64
  scheme: 4x4@75%
  set_inol: '0.16'
  volume: '16'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.72
  scheme: 9x2@75%
  set_inol: '0.08'
  volume: '18'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 4x5@75%
  set_inol: '0.2'
  volume: '20'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.84
  scheme: 7x3@75%
  set_inol: '0.12'
  volume: '21'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.96
  scheme: 8x3@75%
  set_inol: '0.12'
  volume: '24'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.08
  scheme: 9x3@75%
  set_inol: '0.12'
  volume: '27'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.12
  scheme: 7x4@75%
  set_inol: '0.16'
  volume: '28'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.2
  scheme: 10x3@75%
  set_inol: '0.12'
  volume: '30'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.2000000000000002
  scheme: 6x5@75%
  set_inol: '0.2'
  volume: '30'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.28
  scheme: 8x4@75%
  set_inol: '0.16'
  volume: '32'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.4000000000000001
  scheme: 7x5@75%
  set_inol: '0.2'
  volume: '35'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.44
  scheme: 9x4@75%
  set_inol: '0.16'
  volume: '36'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.6
  scheme: 10x4@75%
  set_inol: '0.16'
  volume: '40'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.6
  scheme: 8x5@75%
  set_inol: '0.2'
  volume: '40'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.8
  scheme: 9x5@75%
  set_inol: '0.2'
  volume: '45'
  weight: '42.0'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
