- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '77.35'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '83.3'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '89.25'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '95.2'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '101.15'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '107.1'
  weight_olympic: '107.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '113.05'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
