- exercise_inol: 0.9142857142857143
  scheme: 4x8@65%
  set_inol: '0.228571428571'
  volume: '32'
  week: 1
  weight: '31.85'
  weight_olympic: '32.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x9@70%
  set_inol: '0.3'
  volume: '27'
  week: 2
  weight: '34.3'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  week: 3
  weight: '36.75'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.9
  scheme: 2x9@80%
  set_inol: '0.45'
  volume: '18'
  week: 4
  weight: '39.2'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.9333333333333333
  scheme: 2x7@85%
  set_inol: '0.466666666667'
  volume: '14'
  week: 5
  weight: '41.65'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 6
  weight: '44.1'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '46.55'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
