- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '34.45'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '37.1'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '39.75'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '42.4'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '45.05'
  weight_olympic: '45.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '47.7'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '50.35'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
