- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '133.25'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '143.5'
  weight_olympic: '144.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '153.75'
  weight_olympic: '154.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '164.0'
  weight_olympic: '164.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '174.25'
  weight_olympic: '174.0'
  weight_powerlifting: '175.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '184.5'
  weight_olympic: '185.0'
  weight_powerlifting: '185.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '194.75'
  weight_olympic: '195.0'
  weight_powerlifting: '195.0'
