- exercise_inol: 0.8
  scheme: 3x8@70%
  set_inol: '0.266666666667'
  volume: '24'
  week: 1
  weight: '70.0'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.8
  scheme: 4x5@75%
  set_inol: '0.2'
  volume: '20'
  week: 2
  weight: '75.0'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 3
  weight: '80.0'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8
  scheme: 3x4@85%
  set_inol: '0.266666666667'
  volume: '12'
  week: 4
  weight: '85.0'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 5
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 6
  weight: '95.0'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
