- exercise_inol: 0.8
  scheme: 6x6@55%
  set_inol: '0.133333333333'
  volume: '36'
  week: 1
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 4x8@60%
  set_inol: '0.2'
  volume: '32'
  week: 2
  weight: '60.0'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 3
  weight: '65.0'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 4
  weight: '70.0'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 5
  weight: '75.0'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 6
  weight: '80.0'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 7
  weight: '85.0'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 8
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 9
  weight: '95.0'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
