- exercise_inol: 1.2000000000000002
  scheme: 6x7@65%
  set_inol: '0.2'
  volume: '42'
  week: 1
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.2
  scheme: 4x9@70%
  set_inol: '0.3'
  volume: '36'
  week: 2
  weight: '84.0'
  weight_olympic: '84.0'
  weight_powerlifting: '85.0'
- exercise_inol: 1.2
  scheme: 5x6@75%
  set_inol: '0.24'
  volume: '30'
  week: 3
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 1.2
  scheme: 4x6@80%
  set_inol: '0.3'
  volume: '24'
  week: 4
  weight: '96.0'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x3@85%
  set_inol: '0.2'
  volume: '18'
  week: 5
  weight: '102.0'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 1.2
  scheme: 4x3@90%
  set_inol: '0.3'
  volume: '12'
  week: 6
  weight: '108.0'
  weight_olympic: '108.0'
  weight_powerlifting: '107.5'
- exercise_inol: 1.2000000000000002
  scheme: 6x1@95%
  set_inol: '0.2'
  volume: '6'
  week: 7
  weight: '114.0'
  weight_olympic: '114.0'
  weight_powerlifting: '115.0'
