- exercise_inol: 0.3111111111111111
  scheme: 2x7@55%
  set_inol: '0.155555555556'
  volume: '14'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.3111111111111111
  scheme: 1x14@55%
  set_inol: '0.311111111111'
  volume: '14'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.3333333333333333
  scheme: 5x3@55%
  set_inol: '0.0666666666667'
  volume: '15'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.3333333333333333
  scheme: 3x5@55%
  set_inol: '0.111111111111'
  volume: '15'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.3333333333333333
  scheme: 1x15@55%
  set_inol: '0.333333333333'
  volume: '15'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.35555555555555557
  scheme: 4x4@55%
  set_inol: '0.0888888888889'
  volume: '16'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.35555555555555557
  scheme: 2x8@55%
  set_inol: '0.177777777778'
  volume: '16'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.35555555555555557
  scheme: 1x16@55%
  set_inol: '0.355555555556'
  volume: '16'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.37777777777777777
  scheme: 1x17@55%
  set_inol: '0.377777777778'
  volume: '17'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 6x3@55%
  set_inol: '0.0666666666667'
  volume: '18'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 3x6@55%
  set_inol: '0.133333333333'
  volume: '18'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 2x9@55%
  set_inol: '0.2'
  volume: '18'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4444444444444444
  scheme: 4x5@55%
  set_inol: '0.111111111111'
  volume: '20'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4444444444444444
  scheme: 2x10@55%
  set_inol: '0.222222222222'
  volume: '20'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4444444444444445
  scheme: 5x4@55%
  set_inol: '0.0888888888889'
  volume: '20'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4666666666666667
  scheme: 3x7@55%
  set_inol: '0.155555555556'
  volume: '21'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4888888888888889
  scheme: 2x11@55%
  set_inol: '0.244444444444'
  volume: '22'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5333333333333333
  scheme: 6x4@55%
  set_inol: '0.0888888888889'
  volume: '24'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x6@55%
  set_inol: '0.133333333333'
  volume: '24'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5333333333333333
  scheme: 3x8@55%
  set_inol: '0.177777777778'
  volume: '24'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5333333333333333
  scheme: 2x12@55%
  set_inol: '0.266666666667'
  volume: '24'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5555555555555556
  scheme: 5x5@55%
  set_inol: '0.111111111111'
  volume: '25'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5777777777777777
  scheme: 2x13@55%
  set_inol: '0.288888888889'
  volume: '26'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x9@55%
  set_inol: '0.2'
  volume: '27'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6222222222222222
  scheme: 4x7@55%
  set_inol: '0.155555555556'
  volume: '28'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6222222222222222
  scheme: 2x14@55%
  set_inol: '0.311111111111'
  volume: '28'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6666666666666666
  scheme: 6x5@55%
  set_inol: '0.111111111111'
  volume: '30'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x6@55%
  set_inol: '0.133333333333'
  volume: '30'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6666666666666666
  scheme: 3x10@55%
  set_inol: '0.222222222222'
  volume: '30'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6666666666666666
  scheme: 2x15@55%
  set_inol: '0.333333333333'
  volume: '30'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.7111111111111111
  scheme: 4x8@55%
  set_inol: '0.177777777778'
  volume: '32'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.7111111111111111
  scheme: 2x16@55%
  set_inol: '0.355555555556'
  volume: '32'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.7333333333333333
  scheme: 3x11@55%
  set_inol: '0.244444444444'
  volume: '33'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.7555555555555555
  scheme: 2x17@55%
  set_inol: '0.377777777778'
  volume: '34'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.7777777777777778
  scheme: 5x7@55%
  set_inol: '0.155555555556'
  volume: '35'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 6x6@55%
  set_inol: '0.133333333333'
  volume: '36'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 4x9@55%
  set_inol: '0.2'
  volume: '36'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8
  scheme: 3x12@55%
  set_inol: '0.266666666667'
  volume: '36'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8666666666666666
  scheme: 3x13@55%
  set_inol: '0.288888888889'
  volume: '39'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.8888888888888888
  scheme: 4x10@55%
  set_inol: '0.222222222222'
  volume: '40'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.888888888888889
  scheme: 5x8@55%
  set_inol: '0.177777777778'
  volume: '40'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.9333333333333333
  scheme: 6x7@55%
  set_inol: '0.155555555556'
  volume: '42'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.9333333333333333
  scheme: 3x14@55%
  set_inol: '0.311111111111'
  volume: '42'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.9777777777777777
  scheme: 4x11@55%
  set_inol: '0.244444444444'
  volume: '44'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0
  scheme: 5x9@55%
  set_inol: '0.2'
  volume: '45'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0
  scheme: 3x15@55%
  set_inol: '0.333333333333'
  volume: '45'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0666666666666667
  scheme: 6x8@55%
  set_inol: '0.177777777778'
  volume: '48'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0666666666666667
  scheme: 4x12@55%
  set_inol: '0.266666666667'
  volume: '48'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0666666666666667
  scheme: 3x16@55%
  set_inol: '0.355555555556'
  volume: '48'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.1111111111111112
  scheme: 5x10@55%
  set_inol: '0.222222222222'
  volume: '50'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.1333333333333333
  scheme: 3x17@55%
  set_inol: '0.377777777778'
  volume: '51'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.1555555555555554
  scheme: 4x13@55%
  set_inol: '0.288888888889'
  volume: '52'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x9@55%
  set_inol: '0.2'
  volume: '54'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.222222222222222
  scheme: 5x11@55%
  set_inol: '0.244444444444'
  volume: '55'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.2444444444444445
  scheme: 4x14@55%
  set_inol: '0.311111111111'
  volume: '56'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.3333333333333333
  scheme: 6x10@55%
  set_inol: '0.222222222222'
  volume: '60'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.3333333333333333
  scheme: 5x12@55%
  set_inol: '0.266666666667'
  volume: '60'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.3333333333333333
  scheme: 4x15@55%
  set_inol: '0.333333333333'
  volume: '60'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.4222222222222223
  scheme: 4x16@55%
  set_inol: '0.355555555556'
  volume: '64'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.4444444444444442
  scheme: 5x13@55%
  set_inol: '0.288888888889'
  volume: '65'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.4666666666666666
  scheme: 6x11@55%
  set_inol: '0.244444444444'
  volume: '66'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.511111111111111
  scheme: 4x17@55%
  set_inol: '0.377777777778'
  volume: '68'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.5555555555555556
  scheme: 5x14@55%
  set_inol: '0.311111111111'
  volume: '70'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.6
  scheme: 6x12@55%
  set_inol: '0.266666666667'
  volume: '72'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.6666666666666665
  scheme: 5x15@55%
  set_inol: '0.333333333333'
  volume: '75'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.7333333333333332
  scheme: 6x13@55%
  set_inol: '0.288888888889'
  volume: '78'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.777777777777778
  scheme: 5x16@55%
  set_inol: '0.355555555556'
  volume: '80'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.8666666666666667
  scheme: 6x14@55%
  set_inol: '0.311111111111'
  volume: '84'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.8888888888888888
  scheme: 5x17@55%
  set_inol: '0.377777777778'
  volume: '85'
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
