- exercise_inol: 0.3333333333333333
  scheme: 5x1@85.0%
  set_inol: '0.0666666666667'
  volume: '5'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.3333333333333333
  scheme: 1x5@85.0%
  set_inol: '0.333333333333'
  volume: '5'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.4
  scheme: 3x2@85.0%
  set_inol: '0.133333333333'
  volume: '6'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.4
  scheme: 2x3@85.0%
  set_inol: '0.2'
  volume: '6'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.4
  scheme: 1x6@85.0%
  set_inol: '0.4'
  volume: '6'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.4666666666666667
  scheme: 1x7@85.0%
  set_inol: '0.466666666667'
  volume: '7'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85.0%
  set_inol: '0.133333333333'
  volume: '8'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.5333333333333333
  scheme: 2x4@85.0%
  set_inol: '0.266666666667'
  volume: '8'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85.0%
  set_inol: '0.2'
  volume: '9'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85.0%
  set_inol: '0.133333333333'
  volume: '10'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6666666666666666
  scheme: 2x5@85.0%
  set_inol: '0.333333333333'
  volume: '10'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 4x3@85.0%
  set_inol: '0.2'
  volume: '12'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 3x4@85.0%
  set_inol: '0.266666666667'
  volume: '12'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 2x6@85.0%
  set_inol: '0.4'
  volume: '12'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.9333333333333333
  scheme: 2x7@85.0%
  set_inol: '0.466666666667'
  volume: '14'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.0
  scheme: 5x3@85.0%
  set_inol: '0.2'
  volume: '15'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.0
  scheme: 3x5@85.0%
  set_inol: '0.333333333333'
  volume: '15'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.0666666666666667
  scheme: 4x4@85.0%
  set_inol: '0.266666666667'
  volume: '16'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x6@85.0%
  set_inol: '0.4'
  volume: '18'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.3333333333333333
  scheme: 5x4@85.0%
  set_inol: '0.266666666667'
  volume: '20'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.3333333333333333
  scheme: 4x5@85.0%
  set_inol: '0.333333333333'
  volume: '20'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.4
  scheme: 3x7@85.0%
  set_inol: '0.466666666667'
  volume: '21'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.6
  scheme: 4x6@85.0%
  set_inol: '0.4'
  volume: '24'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.6666666666666665
  scheme: 5x5@85.0%
  set_inol: '0.333333333333'
  volume: '25'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.8666666666666667
  scheme: 4x7@85.0%
  set_inol: '0.466666666667'
  volume: '28'
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
