- exercise_inol: 0.6
  scheme: 4x3@80.0%
  set_inol: '0.15'
  volume: '12'
  week: 1
  weight: '69.6'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.5714285714285714
  scheme: 5x2@82.5%
  set_inol: '0.114285714286'
  volume: '10'
  week: 2
  weight: '71.775'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85.0%
  set_inol: '0.2'
  volume: '9'
  week: 3
  weight: '73.95'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.64
  scheme: 4x2@87.5%
  set_inol: '0.16'
  volume: '8'
  week: 4
  weight: '76.125'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6
  scheme: 2x3@90.0%
  set_inol: '0.3'
  volume: '6'
  week: 5
  weight: '78.3'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 6
  weight: '80.475'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95.0%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '82.65'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
