- exercise_inol: 0.5333333333333333
  scheme: 5x4@62.5%
  set_inol: '0.106666666667'
  volume: '20'
  week: 1
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.49230769230769234
  scheme: 4x4@67.5%
  set_inol: '0.123076923077'
  volume: '16'
  week: 2
  weight: '33.75'
  weight_olympic: '34.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.5454545454545454
  scheme: 5x3@72.5%
  set_inol: '0.109090909091'
  volume: '15'
  week: 3
  weight: '36.25'
  weight_olympic: '36.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x3@77.5%
  set_inol: '0.133333333333'
  volume: '12'
  week: 4
  weight: '38.75'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5142857142857142
  scheme: 3x3@82.5%
  set_inol: '0.171428571429'
  volume: '9'
  week: 5
  weight: '41.25'
  weight_olympic: '41.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.48
  scheme: 3x2@87.5%
  set_inol: '0.16'
  volume: '6'
  week: 6
  weight: '43.75'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 7
  weight: '46.25'
  weight_olympic: '46.0'
  weight_powerlifting: '47.5'
