- exercise_inol: 0.32
  scheme: 4x3@62.5%
  set_inol: '0.08'
  volume: '12'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.32
  scheme: 3x4@62.5%
  set_inol: '0.106666666667'
  volume: '12'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.4
  scheme: 5x3@62.5%
  set_inol: '0.08'
  volume: '15'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.4
  scheme: 3x5@62.5%
  set_inol: '0.133333333333'
  volume: '15'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.4266666666666667
  scheme: 4x4@62.5%
  set_inol: '0.106666666667'
  volume: '16'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.5333333333333333
  scheme: 5x4@62.5%
  set_inol: '0.106666666667'
  volume: '20'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x5@62.5%
  set_inol: '0.133333333333'
  volume: '20'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x5@62.5%
  set_inol: '0.133333333333'
  volume: '25'
  weight: '31.25'
  weight_olympic: '31.0'
  weight_powerlifting: '32.5'
