- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 0.4
  scheme: 1x2@95%
  set_inol: '0.4'
  volume: '2'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 0.8
  scheme: 2x2@95%
  set_inol: '0.4'
  volume: '4'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x1@95%
  set_inol: '0.2'
  volume: '6'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x2@95%
  set_inol: '0.4'
  volume: '6'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 1.4000000000000001
  scheme: 7x1@95%
  set_inol: '0.2'
  volume: '7'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 1.6
  scheme: 8x1@95%
  set_inol: '0.2'
  volume: '8'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
- exercise_inol: 1.6
  scheme: 4x2@95%
  set_inol: '0.4'
  volume: '8'
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
