- exercise_inol: 0.7368421052631579
  scheme: 7x4@62%
  set_inol: '0.105263157895'
  volume: '28'
  week: 1
  weight: '124.0'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.7272727272727273
  scheme: 8x3@67%
  set_inol: '0.0909090909091'
  volume: '24'
  week: 2
  weight: '134.0'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.7142857142857142
  scheme: 5x4@72%
  set_inol: '0.142857142857'
  volume: '20'
  week: 3
  weight: '144.0'
  weight_olympic: '144.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.6956521739130435
  scheme: 8x2@77%
  set_inol: '0.0869565217391'
  volume: '16'
  week: 4
  weight: '154.0'
  weight_olympic: '154.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.6666666666666666
  scheme: 6x2@82%
  set_inol: '0.111111111111'
  volume: '12'
  week: 5
  weight: '164.0'
  weight_olympic: '164.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.6923076923076923
  scheme: 3x3@87%
  set_inol: '0.230769230769'
  volume: '9'
  week: 6
  weight: '174.0'
  weight_olympic: '174.0'
  weight_powerlifting: '175.0'
- exercise_inol: 0.75
  scheme: 6x1@92%
  set_inol: '0.125'
  volume: '6'
  week: 7
  weight: '184.0'
  weight_olympic: '184.0'
  weight_powerlifting: '185.0'
