- exercise_inol: 0.6857142857142857
  scheme: 8x3@65%
  set_inol: '0.0857142857143'
  volume: '24'
  week: 1
  weight: '139.75'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x4@70%
  set_inol: '0.133333333333'
  volume: '20'
  week: 2
  weight: '150.5'
  weight_olympic: '151.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.64
  scheme: 8x2@75%
  set_inol: '0.08'
  volume: '16'
  week: 3
  weight: '161.25'
  weight_olympic: '161.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  week: 4
  weight: '172.0'
  weight_olympic: '172.0'
  weight_powerlifting: '172.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  week: 5
  weight: '182.75'
  weight_olympic: '183.0'
  weight_powerlifting: '182.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '193.5'
  weight_olympic: '194.0'
  weight_powerlifting: '192.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '204.25'
  weight_olympic: '204.0'
  weight_powerlifting: '205.0'
