- exercise_inol: 0.32
  scheme: 4x2@75%
  set_inol: '0.08'
  volume: '8'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.36
  scheme: 3x3@75%
  set_inol: '0.12'
  volume: '9'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.48
  scheme: 6x2@75%
  set_inol: '0.08'
  volume: '12'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.56
  scheme: 7x2@75%
  set_inol: '0.08'
  volume: '14'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.64
  scheme: 8x2@75%
  set_inol: '0.08'
  volume: '16'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.72
  scheme: 9x2@75%
  set_inol: '0.08'
  volume: '18'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.84
  scheme: 7x3@75%
  set_inol: '0.12'
  volume: '21'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.96
  scheme: 8x3@75%
  set_inol: '0.12'
  volume: '24'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 1.08
  scheme: 9x3@75%
  set_inol: '0.12'
  volume: '27'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 1.2
  scheme: 10x3@75%
  set_inol: '0.12'
  volume: '30'
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
