- exercise_inol: 0.75
  scheme: 10x3@60%
  set_inol: '0.075'
  volume: '30'
  week: 1
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.7714285714285715
  scheme: 9x3@65%
  set_inol: '0.0857142857143'
  volume: '27'
  week: 2
  weight: '148.2'
  weight_olympic: '148.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.7000000000000001
  scheme: 7x3@70%
  set_inol: '0.1'
  volume: '21'
  week: 3
  weight: '159.6'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  week: 4
  weight: '171.0'
  weight_olympic: '171.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.75
  scheme: 5x3@80%
  set_inol: '0.15'
  volume: '15'
  week: 5
  weight: '182.4'
  weight_olympic: '182.0'
  weight_powerlifting: '182.5'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 6
  weight: '193.8'
  weight_olympic: '194.0'
  weight_powerlifting: '195.0'
- exercise_inol: 0.7000000000000001
  scheme: 7x1@90%
  set_inol: '0.1'
  volume: '7'
  week: 7
  weight: '205.2'
  weight_olympic: '205.0'
  weight_powerlifting: '205.0'
