- exercise_inol: 0.375
  scheme: 5x3@60%
  set_inol: '0.075'
  volume: '15'
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.44999999999999996
  scheme: 6x3@60%
  set_inol: '0.075'
  volume: '18'
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.525
  scheme: 7x3@60%
  set_inol: '0.075'
  volume: '21'
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.6
  scheme: 8x3@60%
  set_inol: '0.075'
  volume: '24'
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.6749999999999999
  scheme: 9x3@60%
  set_inol: '0.075'
  volume: '27'
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.75
  scheme: 10x3@60%
  set_inol: '0.075'
  volume: '30'
  weight: '136.8'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
