- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '61.75'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '66.5'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '71.25'
  weight_olympic: '71.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '76.0'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '80.75'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '85.5'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '90.25'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
