- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 1
  weight: '33.15'
  weight_olympic: '33.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.6
  scheme: 9x2@70%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 2
  weight: '35.7'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '38.25'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '40.8'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.6
  scheme: 9x1@85%
  set_inol: '0.0666666666667'
  volume: '9'
  week: 5
  weight: '43.35'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '48.45'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
