- exercise_inol: 0.48
  scheme: 6x3@62.5%
  set_inol: '0.08'
  volume: '18'
  week: 1
  weight: '38.125'
  weight_olympic: '38.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.49230769230769234
  scheme: 4x4@67.5%
  set_inol: '0.123076923077'
  volume: '16'
  week: 2
  weight: '41.175'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5454545454545454
  scheme: 5x3@72.5%
  set_inol: '0.109090909091'
  volume: '15'
  week: 3
  weight: '44.225'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.5333333333333333
  scheme: 6x2@77.5%
  set_inol: '0.0888888888889'
  volume: '12'
  week: 4
  weight: '47.275'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.5142857142857142
  scheme: 3x3@82.5%
  set_inol: '0.171428571429'
  volume: '9'
  week: 5
  weight: '50.325'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.48
  scheme: 6x1@87.5%
  set_inol: '0.08'
  volume: '6'
  week: 6
  weight: '53.375'
  weight_olympic: '53.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 7
  weight: '56.425'
  weight_olympic: '56.0'
  weight_powerlifting: '57.5'
