- exercise_inol: 0.6857142857142857
  scheme: 6x4@65%
  set_inol: '0.114285714286'
  volume: '24'
  week: 1
  weight: '58.5'
  weight_olympic: '59.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.7
  scheme: 3x7@70%
  set_inol: '0.233333333333'
  volume: '21'
  week: 2
  weight: '63.0'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  week: 3
  weight: '67.5'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.7
  scheme: 2x7@80%
  set_inol: '0.35'
  volume: '14'
  week: 4
  weight: '72.0'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  week: 5
  weight: '76.5'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '81.0'
  weight_olympic: '81.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '85.5'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
