- exercise_inol: 1.0
  scheme: 7x5@65%
  set_inol: '0.142857142857'
  volume: '35'
  week: 1
  weight: '94.25'
  weight_olympic: '94.0'
  weight_powerlifting: '95.0'
- exercise_inol: 1.0
  scheme: 10x3@70%
  set_inol: '0.1'
  volume: '30'
  week: 2
  weight: '101.5'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '108.75'
  weight_olympic: '109.0'
  weight_powerlifting: '110.0'
- exercise_inol: 1.0
  scheme: 10x2@80%
  set_inol: '0.1'
  volume: '20'
  week: 4
  weight: '116.0'
  weight_olympic: '116.0'
  weight_powerlifting: '115.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '123.25'
  weight_olympic: '123.0'
  weight_powerlifting: '122.5'
- exercise_inol: 1.0
  scheme: 10x1@90%
  set_inol: '0.1'
  volume: '10'
  week: 6
  weight: '130.5'
  weight_olympic: '131.0'
  weight_powerlifting: '130.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '137.75'
  weight_olympic: '138.0'
  weight_powerlifting: '137.5'
