- exercise_inol: 0.36363636363636365
  scheme: 4x3@67%
  set_inol: '0.0909090909091'
  volume: '12'
  week: 1
  weight: '90.45'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.42857142857142855
  scheme: 4x3@72%
  set_inol: '0.107142857143'
  volume: '12'
  week: 2
  weight: '97.2'
  weight_olympic: '97.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.3913043478260869
  scheme: 3x3@77%
  set_inol: '0.130434782609'
  volume: '9'
  week: 3
  weight: '103.95'
  weight_olympic: '104.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.4444444444444444
  scheme: 4x2@82%
  set_inol: '0.111111111111'
  volume: '8'
  week: 4
  weight: '110.7'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.38461538461538464
  scheme: 5x1@87%
  set_inol: '0.0769230769231'
  volume: '5'
  week: 5
  weight: '117.45'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.375
  scheme: 3x1@92%
  set_inol: '0.125'
  volume: '3'
  week: 6
  weight: '124.2'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.3333333333333333
  scheme: 1x1@97%
  set_inol: '0.333333333333'
  volume: '1'
  week: 7
  weight: '130.95'
  weight_olympic: '131.0'
  weight_powerlifting: '130.0'
