- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '118.625'
  weight_olympic: '119.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '127.75'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '136.875'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '146.0'
  weight_olympic: '146.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '155.125'
  weight_olympic: '155.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '164.25'
  weight_olympic: '164.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '173.375'
  weight_olympic: '173.0'
  weight_powerlifting: '172.5'
