- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '29.9'
  weight_olympic: '30.0'
  weight_powerlifting: '30.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '32.2'
  weight_olympic: '32.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '34.5'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '36.8'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '39.1'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '41.4'
  weight_olympic: '41.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '43.7'
  weight_olympic: '44.0'
  weight_powerlifting: '42.5'
