- exercise_inol: 0.8181818181818182
  scheme: 9x3@67%
  set_inol: '0.0909090909091'
  volume: '27'
  week: 1
  weight: '32.16'
  weight_olympic: '32.0'
  weight_powerlifting: '32.5'
- exercise_inol: 0.75
  scheme: 7x3@72%
  set_inol: '0.107142857143'
  volume: '21'
  week: 2
  weight: '34.56'
  weight_olympic: '35.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.7826086956521738
  scheme: 9x2@77%
  set_inol: '0.0869565217391'
  volume: '18'
  week: 3
  weight: '36.96'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.7777777777777777
  scheme: 7x2@82%
  set_inol: '0.111111111111'
  volume: '14'
  week: 4
  weight: '39.36'
  weight_olympic: '39.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.7692307692307693
  scheme: 10x1@87%
  set_inol: '0.0769230769231'
  volume: '10'
  week: 5
  weight: '41.76'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.75
  scheme: 6x1@92%
  set_inol: '0.125'
  volume: '6'
  week: 6
  weight: '44.16'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6666666666666666
  scheme: 2x1@97%
  set_inol: '0.333333333333'
  volume: '2'
  week: 7
  weight: '46.56'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
