- exercise_inol: 0.3125
  scheme: 5x1@84%
  set_inol: '0.0625'
  volume: '5'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.3125
  scheme: 1x5@84%
  set_inol: '0.3125'
  volume: '5'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.375
  scheme: 6x1@84%
  set_inol: '0.0625'
  volume: '6'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.375
  scheme: 3x2@84%
  set_inol: '0.125'
  volume: '6'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.375
  scheme: 2x3@84%
  set_inol: '0.1875'
  volume: '6'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4375
  scheme: 7x1@84%
  set_inol: '0.0625'
  volume: '7'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5
  scheme: 8x1@84%
  set_inol: '0.0625'
  volume: '8'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5
  scheme: 4x2@84%
  set_inol: '0.125'
  volume: '8'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5
  scheme: 2x4@84%
  set_inol: '0.25'
  volume: '8'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5625
  scheme: 9x1@84%
  set_inol: '0.0625'
  volume: '9'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.5625
  scheme: 3x3@84%
  set_inol: '0.1875'
  volume: '9'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.625
  scheme: 10x1@84%
  set_inol: '0.0625'
  volume: '10'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.625
  scheme: 5x2@84%
  set_inol: '0.125'
  volume: '10'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.625
  scheme: 2x5@84%
  set_inol: '0.3125'
  volume: '10'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.75
  scheme: 6x2@84%
  set_inol: '0.125'
  volume: '12'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.75
  scheme: 4x3@84%
  set_inol: '0.1875'
  volume: '12'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.75
  scheme: 3x4@84%
  set_inol: '0.25'
  volume: '12'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.875
  scheme: 7x2@84%
  set_inol: '0.125'
  volume: '14'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.9375
  scheme: 5x3@84%
  set_inol: '0.1875'
  volume: '15'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.9375
  scheme: 3x5@84%
  set_inol: '0.3125'
  volume: '15'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0
  scheme: 8x2@84%
  set_inol: '0.125'
  volume: '16'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.0
  scheme: 4x4@84%
  set_inol: '0.25'
  volume: '16'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.125
  scheme: 9x2@84%
  set_inol: '0.125'
  volume: '18'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.125
  scheme: 6x3@84%
  set_inol: '0.1875'
  volume: '18'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.25
  scheme: 10x2@84%
  set_inol: '0.125'
  volume: '20'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.25
  scheme: 5x4@84%
  set_inol: '0.25'
  volume: '20'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.25
  scheme: 4x5@84%
  set_inol: '0.3125'
  volume: '20'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.3125
  scheme: 7x3@84%
  set_inol: '0.1875'
  volume: '21'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.5
  scheme: 8x3@84%
  set_inol: '0.1875'
  volume: '24'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.5
  scheme: 6x4@84%
  set_inol: '0.25'
  volume: '24'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.5625
  scheme: 5x5@84%
  set_inol: '0.3125'
  volume: '25'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.6875
  scheme: 9x3@84%
  set_inol: '0.1875'
  volume: '27'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.75
  scheme: 7x4@84%
  set_inol: '0.25'
  volume: '28'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.875
  scheme: 10x3@84%
  set_inol: '0.1875'
  volume: '30'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 1.875
  scheme: 6x5@84%
  set_inol: '0.3125'
  volume: '30'
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
