- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 1
  weight: '40.8'
  weight_olympic: '41.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.7777777777777777
  scheme: 7x2@82%
  set_inol: '0.111111111111'
  volume: '14'
  week: 2
  weight: '41.82'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.75
  scheme: 6x2@84%
  set_inol: '0.125'
  volume: '12'
  week: 3
  weight: '42.84'
  weight_olympic: '43.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.8571428571428571
  scheme: 6x2@86%
  set_inol: '0.142857142857'
  volume: '12'
  week: 4
  weight: '43.86'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8333333333333333
  scheme: 10x1@88%
  set_inol: '0.0833333333333'
  volume: '10'
  week: 5
  weight: '44.88'
  weight_olympic: '45.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.75
  scheme: 6x1@92%
  set_inol: '0.125'
  volume: '6'
  week: 7
  weight: '46.92'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
