- exercise_inol: 0.5818181818181818
  scheme: 8x2@72.5%
  set_inol: '0.0727272727273'
  volume: '16'
  week: 1
  weight: '36.975'
  weight_olympic: '37.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6222222222222222
  scheme: 7x2@77.5%
  set_inol: '0.0888888888889'
  volume: '14'
  week: 2
  weight: '39.525'
  weight_olympic: '40.0'
  weight_powerlifting: '40.0'
- exercise_inol: 0.5714285714285714
  scheme: 10x1@82.5%
  set_inol: '0.0571428571429'
  volume: '10'
  week: 3
  weight: '42.075'
  weight_olympic: '42.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.56
  scheme: 7x1@87.5%
  set_inol: '0.08'
  volume: '7'
  week: 4
  weight: '44.625'
  weight_olympic: '45.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 5
  weight: '47.175'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
