- exercise_inol: 0.30000000000000004
  scheme: 3x1@90%
  set_inol: '0.1'
  volume: '3'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.4
  scheme: 2x2@90%
  set_inol: '0.2'
  volume: '4'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.5
  scheme: 5x1@90%
  set_inol: '0.1'
  volume: '5'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x2@90%
  set_inol: '0.2'
  volume: '6'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.7000000000000001
  scheme: 7x1@90%
  set_inol: '0.1'
  volume: '7'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.9
  scheme: 9x1@90%
  set_inol: '0.1'
  volume: '9'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.0
  scheme: 10x1@90%
  set_inol: '0.1'
  volume: '10'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.2
  scheme: 4x3@90%
  set_inol: '0.3'
  volume: '12'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x2@90%
  set_inol: '0.2'
  volume: '12'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.4000000000000001
  scheme: 7x2@90%
  set_inol: '0.2'
  volume: '14'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.5
  scheme: 5x3@90%
  set_inol: '0.3'
  volume: '15'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.6
  scheme: 8x2@90%
  set_inol: '0.2'
  volume: '16'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.7999999999999998
  scheme: 6x3@90%
  set_inol: '0.3'
  volume: '18'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
- exercise_inol: 1.8
  scheme: 9x2@90%
  set_inol: '0.2'
  volume: '18'
  weight: '45.9'
  weight_olympic: '46.0'
  weight_powerlifting: '45.0'
