- exercise_inol: 0.9142857142857143
  scheme: 8x4@65%
  set_inol: '0.114285714286'
  volume: '32'
  week: 1
  weight: '35.75'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.9
  scheme: 9x3@70%
  set_inol: '0.1'
  volume: '27'
  week: 2
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.96
  scheme: 8x3@75%
  set_inol: '0.12'
  volume: '24'
  week: 3
  weight: '41.25'
  weight_olympic: '41.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.9
  scheme: 9x2@80%
  set_inol: '0.1'
  volume: '18'
  week: 4
  weight: '44.0'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.9333333333333333
  scheme: 7x2@85%
  set_inol: '0.133333333333'
  volume: '14'
  week: 5
  weight: '46.75'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.9
  scheme: 9x1@90%
  set_inol: '0.1'
  volume: '9'
  week: 6
  weight: '49.5'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '52.25'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
