- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '133.25'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '143.5'
  weight_olympic: '144.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '153.75'
  weight_olympic: '154.0'
  weight_powerlifting: '155.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '164.0'
  weight_olympic: '164.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '174.25'
  weight_olympic: '174.0'
  weight_powerlifting: '175.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '184.5'
  weight_olympic: '185.0'
  weight_powerlifting: '185.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '194.75'
  weight_olympic: '195.0'
  weight_powerlifting: '195.0'
