- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '43.875'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '47.25'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '50.625'
  weight_olympic: '51.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '54.0'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '57.375'
  weight_olympic: '57.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '64.125'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
