- exercise_inol: 0.45
  scheme: 2x9@60%
  set_inol: '0.225'
  volume: '18'
  week: 1
  weight: '102.0'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.45714285714285713
  scheme: 4x4@65%
  set_inol: '0.114285714286'
  volume: '16'
  week: 2
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.4666666666666667
  scheme: 2x7@70%
  set_inol: '0.233333333333'
  volume: '14'
  week: 3
  weight: '119.0'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  week: 4
  weight: '127.5'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.44999999999999996
  scheme: 3x3@80%
  set_inol: '0.15'
  volume: '9'
  week: 5
  weight: '136.0'
  weight_olympic: '136.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  week: 6
  weight: '144.5'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 7
  weight: '153.0'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 8
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
