- exercise_inol: 0.9142857142857143
  scheme: 4x8@65%
  set_inol: '0.228571428571'
  volume: '32'
  week: 1
  weight: '52.0'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x9@70%
  set_inol: '0.3'
  volume: '27'
  week: 2
  weight: '56.0'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  week: 3
  weight: '60.0'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.9
  scheme: 2x9@80%
  set_inol: '0.45'
  volume: '18'
  week: 4
  weight: '64.0'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.9333333333333333
  scheme: 2x7@85%
  set_inol: '0.466666666667'
  volume: '14'
  week: 5
  weight: '68.0'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 6
  weight: '72.0'
  weight_olympic: '72.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '76.0'
  weight_olympic: '76.0'
  weight_powerlifting: '75.0'
