- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '53.625'
  weight_olympic: '54.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '57.75'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '61.875'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '66.0'
  weight_olympic: '66.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '70.125'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '74.25'
  weight_olympic: '74.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '78.375'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
