- exercise_inol: 0.6666666666666666
  scheme: 5x2@85.0%
  set_inol: '0.133333333333'
  volume: '10'
  week: 1
  weight: '62.05'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.72
  scheme: 3x3@87.5%
  set_inol: '0.24'
  volume: '9'
  week: 2
  weight: '63.875'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x2@90.0%
  set_inol: '0.2'
  volume: '6'
  week: 3
  weight: '65.7'
  weight_olympic: '66.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x1@92.5%
  set_inol: '0.133333333333'
  volume: '5'
  week: 4
  weight: '67.525'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95.0%
  set_inol: '0.2'
  volume: '3'
  week: 5
  weight: '69.35'
  weight_olympic: '69.0'
  weight_powerlifting: '70.0'
