- exercise_inol: 0.6222222222222222
  scheme: 2x7@77.5%
  set_inol: '0.311111111111'
  volume: '14'
  week: 1
  weight: '54.25'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.6
  scheme: 4x3@80.0%
  set_inol: '0.15'
  volume: '12'
  week: 2
  weight: '56.0'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.5714285714285714
  scheme: 5x2@82.5%
  set_inol: '0.114285714286'
  volume: '10'
  week: 3
  weight: '57.75'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85.0%
  set_inol: '0.2'
  volume: '9'
  week: 4
  weight: '59.5'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.64
  scheme: 4x2@87.5%
  set_inol: '0.16'
  volume: '8'
  week: 5
  weight: '61.25'
  weight_olympic: '61.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.6
  scheme: 2x3@90.0%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '63.0'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 7
  weight: '64.75'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95.0%
  set_inol: '0.2'
  volume: '3'
  week: 8
  weight: '66.5'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
