- exercise_inol: 0.5
  scheme: 5x2@80.0%
  set_inol: '0.1'
  volume: '10'
  week: 1
  weight: '56.8'
  weight_olympic: '57.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.5142857142857142
  scheme: 3x3@82.5%
  set_inol: '0.171428571429'
  volume: '9'
  week: 2
  weight: '58.575'
  weight_olympic: '59.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85.0%
  set_inol: '0.133333333333'
  volume: '8'
  week: 3
  weight: '60.35'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.48
  scheme: 3x2@87.5%
  set_inol: '0.16'
  volume: '6'
  week: 4
  weight: '62.125'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.5
  scheme: 5x1@90.0%
  set_inol: '0.1'
  volume: '5'
  week: 5
  weight: '63.9'
  weight_olympic: '64.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x1@92.5%
  set_inol: '0.133333333333'
  volume: '4'
  week: 6
  weight: '65.675'
  weight_olympic: '66.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.4
  scheme: 2x1@95.0%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '67.45'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
