- exercise_inol: 0.30000000000000004
  scheme: 3x1@90.0%
  set_inol: '0.1'
  volume: '3'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 4x1@90.0%
  set_inol: '0.1'
  volume: '4'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 2x2@90.0%
  set_inol: '0.2'
  volume: '4'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 1x4@90.0%
  set_inol: '0.4'
  volume: '4'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.5
  scheme: 5x1@90.0%
  set_inol: '0.1'
  volume: '5'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6
  scheme: 2x3@90.0%
  set_inol: '0.3'
  volume: '6'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x2@90.0%
  set_inol: '0.2'
  volume: '6'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 4x2@90.0%
  set_inol: '0.2'
  volume: '8'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 2x4@90.0%
  set_inol: '0.4'
  volume: '8'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90.0%
  set_inol: '0.3'
  volume: '9'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.0
  scheme: 5x2@90.0%
  set_inol: '0.2'
  volume: '10'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.2
  scheme: 4x3@90.0%
  set_inol: '0.3'
  volume: '12'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x4@90.0%
  set_inol: '0.4'
  volume: '12'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.5
  scheme: 5x3@90.0%
  set_inol: '0.3'
  volume: '15'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.6
  scheme: 4x4@90.0%
  set_inol: '0.4'
  volume: '16'
  weight: '60.75'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
