- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '50.375'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '54.25'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '58.125'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '62.0'
  weight_olympic: '62.0'
  weight_powerlifting: '62.5'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '65.875'
  weight_olympic: '66.0'
  weight_powerlifting: '65.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '69.75'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '73.625'
  weight_olympic: '74.0'
  weight_powerlifting: '72.5'
