- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '68.25'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '73.5'
  weight_olympic: '74.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '78.75'
  weight_olympic: '79.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '84.0'
  weight_olympic: '84.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '89.25'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '94.5'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '99.75'
  weight_olympic: '100.0'
  weight_powerlifting: '100.0'
