- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 1
  weight: '89.05'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '95.9'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '102.75'
  weight_olympic: '103.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '109.6'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '116.45'
  weight_olympic: '116.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '123.3'
  weight_olympic: '123.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '130.15'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
