- exercise_inol: 0.6
  scheme: 7x3@65%
  set_inol: '0.0857142857143'
  volume: '21'
  week: 1
  weight: '87.75'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '94.5'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '101.25'
  weight_olympic: '101.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '108.0'
  weight_olympic: '108.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '114.75'
  weight_olympic: '115.0'
  weight_powerlifting: '115.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '121.5'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '128.25'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
