- exercise_inol: 0.5142857142857142
  scheme: 3x6@65%
  set_inol: '0.171428571429'
  volume: '18'
  week: 1
  weight: '85.8'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.5
  scheme: 5x3@70%
  set_inol: '0.1'
  volume: '15'
  week: 2
  weight: '92.4'
  weight_olympic: '92.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  week: 3
  weight: '99.0'
  weight_olympic: '99.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.5
  scheme: 5x2@80%
  set_inol: '0.1'
  volume: '10'
  week: 4
  weight: '105.6'
  weight_olympic: '106.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85%
  set_inol: '0.133333333333'
  volume: '8'
  week: 5
  weight: '112.2'
  weight_olympic: '112.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.5
  scheme: 5x1@90%
  set_inol: '0.1'
  volume: '5'
  week: 6
  weight: '118.8'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '125.4'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
