- exercise_inol: 0.5
  scheme: 3x5@70%
  set_inol: '0.166666666667'
  volume: '15'
  week: 1
  weight: '98.0'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.48
  scheme: 2x6@75%
  set_inol: '0.24'
  volume: '12'
  week: 2
  weight: '105.0'
  weight_olympic: '105.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.5
  scheme: 2x5@80%
  set_inol: '0.25'
  volume: '10'
  week: 3
  weight: '112.0'
  weight_olympic: '112.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.5333333333333333
  scheme: 2x4@85%
  set_inol: '0.266666666667'
  volume: '8'
  week: 4
  weight: '119.0'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.5
  scheme: 5x1@90%
  set_inol: '0.1'
  volume: '5'
  week: 5
  weight: '126.0'
  weight_olympic: '126.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 6
  weight: '133.0'
  weight_olympic: '133.0'
  weight_powerlifting: '132.5'
