- exercise_inol: 0.32
  scheme: 4x1@87.5%
  set_inol: '0.08'
  volume: '4'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.32
  scheme: 2x2@87.5%
  set_inol: '0.16'
  volume: '4'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.32
  scheme: 1x4@87.5%
  set_inol: '0.32'
  volume: '4'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 5x1@87.5%
  set_inol: '0.08'
  volume: '5'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 1x5@87.5%
  set_inol: '0.4'
  volume: '5'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.48
  scheme: 3x2@87.5%
  set_inol: '0.16'
  volume: '6'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.48
  scheme: 2x3@87.5%
  set_inol: '0.24'
  volume: '6'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.48
  scheme: 1x6@87.5%
  set_inol: '0.48'
  volume: '6'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.64
  scheme: 4x2@87.5%
  set_inol: '0.16'
  volume: '8'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.64
  scheme: 2x4@87.5%
  set_inol: '0.32'
  volume: '8'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.72
  scheme: 3x3@87.5%
  set_inol: '0.24'
  volume: '9'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 5x2@87.5%
  set_inol: '0.16'
  volume: '10'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.8
  scheme: 2x5@87.5%
  set_inol: '0.4'
  volume: '10'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.96
  scheme: 4x3@87.5%
  set_inol: '0.24'
  volume: '12'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.96
  scheme: 3x4@87.5%
  set_inol: '0.32'
  volume: '12'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.96
  scheme: 2x6@87.5%
  set_inol: '0.48'
  volume: '12'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.2
  scheme: 5x3@87.5%
  set_inol: '0.24'
  volume: '15'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x5@87.5%
  set_inol: '0.4'
  volume: '15'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.28
  scheme: 4x4@87.5%
  set_inol: '0.32'
  volume: '16'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.44
  scheme: 3x6@87.5%
  set_inol: '0.48'
  volume: '18'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.6
  scheme: 5x4@87.5%
  set_inol: '0.32'
  volume: '20'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.6
  scheme: 4x5@87.5%
  set_inol: '0.4'
  volume: '20'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 1.92
  scheme: 4x6@87.5%
  set_inol: '0.48'
  volume: '24'
  weight: '59.0625'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
