- exercise_inol: 1.0
  scheme: 7x5@65%
  set_inol: '0.142857142857'
  volume: '35'
  week: 1
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 1.0
  scheme: 10x3@70%
  set_inol: '0.1'
  volume: '30'
  week: 2
  weight: '119.0'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '127.5'
  weight_olympic: '128.0'
  weight_powerlifting: '127.5'
- exercise_inol: 1.0
  scheme: 10x2@80%
  set_inol: '0.1'
  volume: '20'
  week: 4
  weight: '136.0'
  weight_olympic: '136.0'
  weight_powerlifting: '135.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '144.5'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 1.0
  scheme: 10x1@90%
  set_inol: '0.1'
  volume: '10'
  week: 6
  weight: '153.0'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '161.5'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
