- exercise_inol: 0.6857142857142857
  scheme: 8x3@65%
  set_inol: '0.0857142857143'
  volume: '24'
  week: 1
  weight: '159.25'
  weight_olympic: '159.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x4@70%
  set_inol: '0.133333333333'
  volume: '20'
  week: 2
  weight: '171.5'
  weight_olympic: '172.0'
  weight_powerlifting: '172.5'
- exercise_inol: 0.64
  scheme: 8x2@75%
  set_inol: '0.08'
  volume: '16'
  week: 3
  weight: '183.75'
  weight_olympic: '184.0'
  weight_powerlifting: '185.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  week: 4
  weight: '196.0'
  weight_olympic: '196.0'
  weight_powerlifting: '195.0'
- exercise_inol: 0.6666666666666666
  scheme: 5x2@85%
  set_inol: '0.133333333333'
  volume: '10'
  week: 5
  weight: '208.25'
  weight_olympic: '208.0'
  weight_powerlifting: '207.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '220.5'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '232.75'
  weight_olympic: '233.0'
  weight_powerlifting: '232.5'
