- exercise_inol: 0.7142857142857142
  scheme: 5x4@72%
  set_inol: '0.142857142857'
  volume: '20'
  week: 1
  weight: '172.8'
  weight_olympic: '173.0'
  weight_powerlifting: '172.5'
- exercise_inol: 0.6956521739130435
  scheme: 8x2@77%
  set_inol: '0.0869565217391'
  volume: '16'
  week: 2
  weight: '184.8'
  weight_olympic: '185.0'
  weight_powerlifting: '185.0'
- exercise_inol: 0.6666666666666666
  scheme: 6x2@82%
  set_inol: '0.111111111111'
  volume: '12'
  week: 3
  weight: '196.8'
  weight_olympic: '197.0'
  weight_powerlifting: '197.5'
- exercise_inol: 0.6923076923076923
  scheme: 3x3@87%
  set_inol: '0.230769230769'
  volume: '9'
  week: 4
  weight: '208.8'
  weight_olympic: '209.0'
  weight_powerlifting: '210.0'
- exercise_inol: 0.75
  scheme: 6x1@92%
  set_inol: '0.125'
  volume: '6'
  week: 5
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
