- exercise_inol: 0.375
  scheme: 3x1@92%
  set_inol: '0.125'
  volume: '3'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.375
  scheme: 1x3@92%
  set_inol: '0.375'
  volume: '3'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.5
  scheme: 4x1@92%
  set_inol: '0.125'
  volume: '4'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.5
  scheme: 2x2@92%
  set_inol: '0.25'
  volume: '4'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.625
  scheme: 5x1@92%
  set_inol: '0.125'
  volume: '5'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.75
  scheme: 6x1@92%
  set_inol: '0.125'
  volume: '6'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.75
  scheme: 3x2@92%
  set_inol: '0.25'
  volume: '6'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.75
  scheme: 2x3@92%
  set_inol: '0.375'
  volume: '6'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 0.875
  scheme: 7x1@92%
  set_inol: '0.125'
  volume: '7'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.0
  scheme: 8x1@92%
  set_inol: '0.125'
  volume: '8'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.0
  scheme: 4x2@92%
  set_inol: '0.25'
  volume: '8'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.125
  scheme: 3x3@92%
  set_inol: '0.375'
  volume: '9'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.25
  scheme: 5x2@92%
  set_inol: '0.25'
  volume: '10'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.5
  scheme: 6x2@92%
  set_inol: '0.25'
  volume: '12'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.5
  scheme: 4x3@92%
  set_inol: '0.375'
  volume: '12'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.75
  scheme: 7x2@92%
  set_inol: '0.25'
  volume: '14'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
- exercise_inol: 1.875
  scheme: 5x3@92%
  set_inol: '0.375'
  volume: '15'
  weight: '220.8'
  weight_olympic: '221.0'
  weight_powerlifting: '220.0'
