- exercise_inol: 0.9142857142857143
  scheme: 8x4@65%
  set_inol: '0.114285714286'
  volume: '32'
  week: 1
  weight: '152.75'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.9333333333333333
  scheme: 7x4@70%
  set_inol: '0.133333333333'
  volume: '28'
  week: 2
  weight: '164.5'
  weight_olympic: '165.0'
  weight_powerlifting: '165.0'
- exercise_inol: 0.96
  scheme: 8x3@75%
  set_inol: '0.12'
  volume: '24'
  week: 3
  weight: '176.25'
  weight_olympic: '176.0'
  weight_powerlifting: '177.5'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  week: 4
  weight: '188.0'
  weight_olympic: '188.0'
  weight_powerlifting: '187.5'
- exercise_inol: 0.9333333333333333
  scheme: 7x2@85%
  set_inol: '0.133333333333'
  volume: '14'
  week: 5
  weight: '199.75'
  weight_olympic: '200.0'
  weight_powerlifting: '200.0'
- exercise_inol: 0.8999999999999999
  scheme: 3x3@90%
  set_inol: '0.3'
  volume: '9'
  week: 6
  weight: '211.5'
  weight_olympic: '212.0'
  weight_powerlifting: '212.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '223.25'
  weight_olympic: '223.0'
  weight_powerlifting: '222.5'
