- exercise_inol: 0.5714285714285714
  scheme: 5x4@65%
  set_inol: '0.114285714286'
  volume: '20'
  week: 1
  weight: '84.5'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x4@70%
  set_inol: '0.133333333333'
  volume: '16'
  week: 2
  weight: '91.0'
  weight_olympic: '91.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.56
  scheme: 2x7@75%
  set_inol: '0.28'
  volume: '14'
  week: 3
  weight: '97.5'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '104.0'
  weight_olympic: '104.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.5333333333333333
  scheme: 4x2@85%
  set_inol: '0.133333333333'
  volume: '8'
  week: 5
  weight: '110.5'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '117.0'
  weight_olympic: '117.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '123.5'
  weight_olympic: '124.0'
  weight_powerlifting: '122.5'
