- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '136.5'
  weight_olympic: '137.0'
  weight_powerlifting: '137.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '147.0'
  weight_olympic: '147.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '157.5'
  weight_olympic: '158.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 4
  weight: '168.0'
  weight_olympic: '168.0'
  weight_powerlifting: '167.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '178.5'
  weight_olympic: '179.0'
  weight_powerlifting: '177.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '189.0'
  weight_olympic: '189.0'
  weight_powerlifting: '190.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '199.5'
  weight_olympic: '200.0'
  weight_powerlifting: '200.0'
