- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '102.7'
  weight_olympic: '103.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 2
  weight: '110.6'
  weight_olympic: '111.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '118.5'
  weight_olympic: '119.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '126.4'
  weight_olympic: '126.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 5
  weight: '134.3'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '142.2'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '150.1'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
