- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '89.05'
  weight_olympic: '89.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '95.9'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '102.75'
  weight_olympic: '103.0'
  weight_powerlifting: '102.5'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '109.6'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '116.45'
  weight_olympic: '116.0'
  weight_powerlifting: '117.5'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '123.3'
  weight_olympic: '123.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '130.15'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
