- exercise_inol: 0.30000000000000004
  scheme: 3x4@60%
  set_inol: '0.1'
  volume: '12'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.375
  scheme: 5x3@60%
  set_inol: '0.075'
  volume: '15'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.375
  scheme: 3x5@60%
  set_inol: '0.125'
  volume: '15'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.44999999999999996
  scheme: 6x3@60%
  set_inol: '0.075'
  volume: '18'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.5
  scheme: 5x4@60%
  set_inol: '0.1'
  volume: '20'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.5
  scheme: 4x5@60%
  set_inol: '0.125'
  volume: '20'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.525
  scheme: 7x3@60%
  set_inol: '0.075'
  volume: '21'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6
  scheme: 8x3@60%
  set_inol: '0.075'
  volume: '24'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x4@60%
  set_inol: '0.1'
  volume: '24'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.625
  scheme: 5x5@60%
  set_inol: '0.125'
  volume: '25'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.6749999999999999
  scheme: 9x3@60%
  set_inol: '0.075'
  volume: '27'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.7000000000000001
  scheme: 7x4@60%
  set_inol: '0.1'
  volume: '28'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.75
  scheme: 10x3@60%
  set_inol: '0.075'
  volume: '30'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.75
  scheme: 6x5@60%
  set_inol: '0.125'
  volume: '30'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 8x4@60%
  set_inol: '0.1'
  volume: '32'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.875
  scheme: 7x5@60%
  set_inol: '0.125'
  volume: '35'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.9
  scheme: 9x4@60%
  set_inol: '0.1'
  volume: '36'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.0
  scheme: 10x4@60%
  set_inol: '0.1'
  volume: '40'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.0
  scheme: 8x5@60%
  set_inol: '0.125'
  volume: '40'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.125
  scheme: 9x5@60%
  set_inol: '0.125'
  volume: '45'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 1.25
  scheme: 10x5@60%
  set_inol: '0.125'
  volume: '50'
  weight: '78.0'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
