- exercise_inol: 0.6000000000000001
  scheme: 3x9@55%
  set_inol: '0.2'
  volume: '27'
  week: 1
  weight: '95.7'
  weight_olympic: '96.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.6
  scheme: 4x6@60%
  set_inol: '0.15'
  volume: '24'
  week: 2
  weight: '104.4'
  weight_olympic: '104.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 3
  weight: '113.1'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 4
  weight: '121.8'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 5
  weight: '130.5'
  weight_olympic: '131.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 6
  weight: '139.2'
  weight_olympic: '139.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 7
  weight: '147.9'
  weight_olympic: '148.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 8
  weight: '156.6'
  weight_olympic: '157.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 9
  weight: '165.3'
  weight_olympic: '165.0'
  weight_powerlifting: '165.0'
