- exercise_inol: 1.2000000000000002
  scheme: 6x7@65%
  set_inol: '0.2'
  volume: '42'
  week: 1
  weight: '65.0'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 1.2
  scheme: 4x9@70%
  set_inol: '0.3'
  volume: '36'
  week: 2
  weight: '70.0'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 1.2
  scheme: 5x6@75%
  set_inol: '0.24'
  volume: '30'
  week: 3
  weight: '75.0'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 1.2
  scheme: 4x6@80%
  set_inol: '0.3'
  volume: '24'
  week: 4
  weight: '80.0'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x3@85%
  set_inol: '0.2'
  volume: '18'
  week: 5
  weight: '85.0'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 1.2
  scheme: 4x3@90%
  set_inol: '0.3'
  volume: '12'
  week: 6
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x1@95%
  set_inol: '0.2'
  volume: '6'
  week: 7
  weight: '95.0'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
