- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 1
  weight: '121.8'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 2
  weight: '130.5'
  weight_olympic: '131.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.6
  scheme: 4x3@80%
  set_inol: '0.15'
  volume: '12'
  week: 3
  weight: '139.2'
  weight_olympic: '139.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 4
  weight: '147.9'
  weight_olympic: '148.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 5
  weight: '156.6'
  weight_olympic: '157.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 6
  weight: '165.3'
  weight_olympic: '165.0'
  weight_powerlifting: '165.0'
