- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 1
  weight: '77.0'
  weight_olympic: '77.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 2
  weight: '82.5'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 3
  weight: '88.0'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 4
  weight: '93.5'
  weight_olympic: '94.0'
  weight_powerlifting: '92.5'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 5
  weight: '99.0'
  weight_olympic: '99.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 6
  weight: '104.5'
  weight_olympic: '105.0'
  weight_powerlifting: '105.0'
