- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 1
  weight: '87.5'
  weight_olympic: '88.0'
  weight_powerlifting: '87.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 2
  weight: '93.75'
  weight_olympic: '94.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 3
  weight: '100.0'
  weight_olympic: '100.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 4
  weight: '106.25'
  weight_olympic: '106.0'
  weight_powerlifting: '107.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 5
  weight: '112.5'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 6
  weight: '118.75'
  weight_olympic: '119.0'
  weight_powerlifting: '120.0'
