- exercise_inol: 0.7999999999999999
  scheme: 7x4@65%
  set_inol: '0.114285714286'
  volume: '28'
  week: 1
  weight: '69.55'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.8
  scheme: 8x3@70%
  set_inol: '0.1'
  volume: '24'
  week: 2
  weight: '74.9'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.8
  scheme: 10x2@75%
  set_inol: '0.08'
  volume: '20'
  week: 3
  weight: '80.25'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.8
  scheme: 8x2@80%
  set_inol: '0.1'
  volume: '16'
  week: 4
  weight: '85.6'
  weight_olympic: '86.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '90.95'
  weight_olympic: '91.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.8
  scheme: 8x1@90%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '96.3'
  weight_olympic: '96.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '101.65'
  weight_olympic: '102.0'
  weight_powerlifting: '102.5'
