- exercise_inol: 0.4
  scheme: 6x3@55%
  set_inol: '0.0666666666667'
  volume: '18'
  week: 1
  weight: '55.0'
  weight_olympic: '55.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  week: 2
  weight: '60.0'
  weight_olympic: '60.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.42857142857142855
  scheme: 3x5@65%
  set_inol: '0.142857142857'
  volume: '15'
  week: 3
  weight: '65.0'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 4
  weight: '70.0'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 5
  weight: '75.0'
  weight_olympic: '75.0'
  weight_powerlifting: '75.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 6
  weight: '80.0'
  weight_olympic: '80.0'
  weight_powerlifting: '80.0'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 7
  weight: '85.0'
  weight_olympic: '85.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 8
  weight: '90.0'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 9
  weight: '95.0'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
