- exercise_inol: 0.3125
  scheme: 5x3@52%
  set_inol: '0.0625'
  volume: '15'
  weight: '63.44'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.3125
  scheme: 3x5@52%
  set_inol: '0.104166666667'
  volume: '15'
  weight: '63.44'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.3333333333333333
  scheme: 4x4@52%
  set_inol: '0.0833333333333'
  volume: '16'
  weight: '63.44'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.41666666666666663
  scheme: 5x4@52%
  set_inol: '0.0833333333333'
  volume: '20'
  weight: '63.44'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.4166666666666667
  scheme: 4x5@52%
  set_inol: '0.104166666667'
  volume: '20'
  weight: '63.44'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.5208333333333334
  scheme: 5x5@52%
  set_inol: '0.104166666667'
  volume: '25'
  weight: '63.44'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
