- exercise_inol: 0.30000000000000004
  scheme: 3x4@60%
  set_inol: '0.1'
  volume: '12'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.375
  scheme: 5x3@60%
  set_inol: '0.075'
  volume: '15'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.375
  scheme: 3x5@60%
  set_inol: '0.125'
  volume: '15'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.44999999999999996
  scheme: 6x3@60%
  set_inol: '0.075'
  volume: '18'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.5
  scheme: 5x4@60%
  set_inol: '0.1'
  volume: '20'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.5
  scheme: 4x5@60%
  set_inol: '0.125'
  volume: '20'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x4@60%
  set_inol: '0.1'
  volume: '24'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.625
  scheme: 5x5@60%
  set_inol: '0.125'
  volume: '25'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.75
  scheme: 6x5@60%
  set_inol: '0.125'
  volume: '30'
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
