- exercise_inol: 0.4
  scheme: 4x4@60%
  set_inol: '0.1'
  volume: '16'
  week: 1
  weight: '67.2'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.42857142857142855
  scheme: 3x5@65%
  set_inol: '0.142857142857'
  volume: '15'
  week: 2
  weight: '72.8'
  weight_olympic: '73.0'
  weight_powerlifting: '72.5'
- exercise_inol: 0.4
  scheme: 6x2@70%
  set_inol: '0.0666666666667'
  volume: '12'
  week: 3
  weight: '78.4'
  weight_olympic: '78.0'
  weight_powerlifting: '77.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 4
  weight: '84.0'
  weight_olympic: '84.0'
  weight_powerlifting: '85.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 5
  weight: '89.6'
  weight_olympic: '90.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.4
  scheme: 6x1@85%
  set_inol: '0.0666666666667'
  volume: '6'
  week: 6
  weight: '95.2'
  weight_olympic: '95.0'
  weight_powerlifting: '95.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 7
  weight: '100.8'
  weight_olympic: '101.0'
  weight_powerlifting: '100.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 8
  weight: '106.4'
  weight_olympic: '106.0'
  weight_powerlifting: '107.5'
