- exercise_inol: 0.42857142857142855
  scheme: 3x5@65%
  set_inol: '0.142857142857'
  volume: '15'
  week: 1
  weight: '46.8'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  week: 2
  weight: '50.4'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '54.0'
  weight_olympic: '54.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '57.6'
  weight_olympic: '58.0'
  weight_powerlifting: '57.5'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  week: 5
  weight: '61.2'
  weight_olympic: '61.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '64.8'
  weight_olympic: '65.0'
  weight_powerlifting: '65.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '68.4'
  weight_olympic: '68.0'
  weight_powerlifting: '67.5'
