- exercise_inol: 0.42857142857142855
  scheme: 3x5@65%
  set_inol: '0.142857142857'
  volume: '15'
  week: 1
  weight: '35.75'
  weight_olympic: '36.0'
  weight_powerlifting: '35.0'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  week: 2
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '41.25'
  weight_olympic: '41.0'
  weight_powerlifting: '42.5'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '44.0'
  weight_olympic: '44.0'
  weight_powerlifting: '45.0'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  week: 5
  weight: '46.75'
  weight_olympic: '47.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '49.5'
  weight_olympic: '50.0'
  weight_powerlifting: '50.0'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '52.25'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
