- exercise_inol: 0.42857142857142855
  scheme: 3x5@65%
  set_inol: '0.142857142857'
  volume: '15'
  week: 1
  weight: '48.1'
  weight_olympic: '48.0'
  weight_powerlifting: '47.5'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  week: 2
  weight: '51.8'
  weight_olympic: '52.0'
  weight_powerlifting: '52.5'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  week: 3
  weight: '55.5'
  weight_olympic: '56.0'
  weight_powerlifting: '55.0'
- exercise_inol: 0.4
  scheme: 4x2@80%
  set_inol: '0.1'
  volume: '8'
  week: 4
  weight: '59.2'
  weight_olympic: '59.0'
  weight_powerlifting: '60.0'
- exercise_inol: 0.4
  scheme: 3x2@85%
  set_inol: '0.133333333333'
  volume: '6'
  week: 5
  weight: '62.9'
  weight_olympic: '63.0'
  weight_powerlifting: '62.5'
- exercise_inol: 0.4
  scheme: 4x1@90%
  set_inol: '0.1'
  volume: '4'
  week: 6
  weight: '66.6'
  weight_olympic: '67.0'
  weight_powerlifting: '67.5'
- exercise_inol: 0.4
  scheme: 2x1@95%
  set_inol: '0.2'
  volume: '2'
  week: 7
  weight: '70.3'
  weight_olympic: '70.0'
  weight_powerlifting: '70.0'
