- exercise_inol: 0.30000000000000004
  scheme: 3x3@70%
  set_inol: '0.1'
  volume: '9'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.3333333333333333
  scheme: 5x2@70%
  set_inol: '0.0666666666667'
  volume: '10'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.3333333333333333
  scheme: 2x5@70%
  set_inol: '0.166666666667'
  volume: '10'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.4
  scheme: 4x3@70%
  set_inol: '0.1'
  volume: '12'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.4
  scheme: 3x4@70%
  set_inol: '0.133333333333'
  volume: '12'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5
  scheme: 5x3@70%
  set_inol: '0.1'
  volume: '15'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5
  scheme: 3x5@70%
  set_inol: '0.166666666667'
  volume: '15'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.5333333333333333
  scheme: 4x4@70%
  set_inol: '0.133333333333'
  volume: '16'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6666666666666666
  scheme: 5x4@70%
  set_inol: '0.133333333333'
  volume: '20'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.6666666666666666
  scheme: 4x5@70%
  set_inol: '0.166666666667'
  volume: '20'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
- exercise_inol: 0.8333333333333333
  scheme: 5x5@70%
  set_inol: '0.166666666667'
  volume: '25'
  weight: '38.5'
  weight_olympic: '39.0'
  weight_powerlifting: '37.5'
