- exercise_inol: 0.37209302325581395
  scheme: 4x4@57%
  set_inol: '0.093023255814'
  volume: '16'
  week: 1
  weight: '83.22'
  weight_olympic: '83.0'
  weight_powerlifting: '82.5'
- exercise_inol: 0.39473684210526316
  scheme: 5x3@62%
  set_inol: '0.0789473684211'
  volume: '15'
  week: 2
  weight: '90.52'
  weight_olympic: '91.0'
  weight_powerlifting: '90.0'
- exercise_inol: 0.36363636363636365
  scheme: 4x3@67%
  set_inol: '0.0909090909091'
  volume: '12'
  week: 3
  weight: '97.82'
  weight_olympic: '98.0'
  weight_powerlifting: '97.5'
- exercise_inol: 0.42857142857142855
  scheme: 4x3@72%
  set_inol: '0.107142857143'
  volume: '12'
  week: 4
  weight: '105.12'
  weight_olympic: '105.0'
  weight_powerlifting: '105.0'
- exercise_inol: 0.3913043478260869
  scheme: 3x3@77%
  set_inol: '0.130434782609'
  volume: '9'
  week: 5
  weight: '112.42'
  weight_olympic: '112.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.4444444444444444
  scheme: 4x2@82%
  set_inol: '0.111111111111'
  volume: '8'
  week: 6
  weight: '119.72'
  weight_olympic: '120.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.38461538461538464
  scheme: 5x1@87%
  set_inol: '0.0769230769231'
  volume: '5'
  week: 7
  weight: '127.02'
  weight_olympic: '127.0'
  weight_powerlifting: '127.5'
- exercise_inol: 0.375
  scheme: 3x1@92%
  set_inol: '0.125'
  volume: '3'
  week: 8
  weight: '134.32'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.3333333333333333
  scheme: 1x1@97%
  set_inol: '0.333333333333'
  volume: '1'
  week: 9
  weight: '141.62'
  weight_olympic: '142.0'
  weight_powerlifting: '142.5'
