- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '113.1'
  weight_olympic: '113.0'
  weight_powerlifting: '112.5'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '121.8'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '130.5'
  weight_olympic: '131.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '139.2'
  weight_olympic: '139.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '147.9'
  weight_olympic: '148.0'
  weight_powerlifting: '147.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '156.6'
  weight_olympic: '157.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '165.3'
  weight_olympic: '165.0'
  weight_powerlifting: '165.0'
