- exercise_inol: 0.8571428571428571
  scheme: 6x5@65%
  set_inol: '0.142857142857'
  volume: '30'
  week: 1
  weight: '120.9'
  weight_olympic: '121.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.8333333333333333
  scheme: 5x5@70%
  set_inol: '0.166666666667'
  volume: '25'
  week: 2
  weight: '130.2'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.8400000000000001
  scheme: 3x7@75%
  set_inol: '0.28'
  volume: '21'
  week: 3
  weight: '139.5'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8999999999999999
  scheme: 6x3@80%
  set_inol: '0.15'
  volume: '18'
  week: 4
  weight: '148.8'
  weight_olympic: '149.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '158.1'
  weight_olympic: '158.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '167.4'
  weight_olympic: '167.0'
  weight_powerlifting: '167.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '176.7'
  weight_olympic: '177.0'
  weight_powerlifting: '177.5'
