- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '124.15'
  weight_olympic: '124.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '133.7'
  weight_olympic: '134.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '143.25'
  weight_olympic: '143.0'
  weight_powerlifting: '142.5'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '152.8'
  weight_olympic: '153.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '162.35'
  weight_olympic: '162.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '171.9'
  weight_olympic: '172.0'
  weight_powerlifting: '172.5'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '181.45'
  weight_olympic: '181.0'
  weight_powerlifting: '182.5'
