- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '124.8'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
- exercise_inol: 0.6
  scheme: 2x9@70%
  set_inol: '0.3'
  volume: '18'
  week: 2
  weight: '134.4'
  weight_olympic: '134.0'
  weight_powerlifting: '135.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  week: 3
  weight: '144.0'
  weight_olympic: '144.0'
  weight_powerlifting: '145.0'
- exercise_inol: 0.6
  scheme: 2x6@80%
  set_inol: '0.3'
  volume: '12'
  week: 4
  weight: '153.6'
  weight_olympic: '154.0'
  weight_powerlifting: '152.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '163.2'
  weight_olympic: '163.0'
  weight_powerlifting: '162.5'
- exercise_inol: 0.6
  scheme: 2x3@90%
  set_inol: '0.3'
  volume: '6'
  week: 6
  weight: '172.8'
  weight_olympic: '173.0'
  weight_powerlifting: '172.5'
