- exercise_inol: 0.32
  scheme: 4x2@75%
  set_inol: '0.08'
  volume: '8'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.32
  scheme: 2x4@75%
  set_inol: '0.16'
  volume: '8'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.32
  scheme: 1x8@75%
  set_inol: '0.32'
  volume: '8'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.36
  scheme: 3x3@75%
  set_inol: '0.12'
  volume: '9'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.36
  scheme: 1x9@75%
  set_inol: '0.36'
  volume: '9'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.4
  scheme: 5x2@75%
  set_inol: '0.08'
  volume: '10'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.4
  scheme: 2x5@75%
  set_inol: '0.2'
  volume: '10'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.4
  scheme: 1x10@75%
  set_inol: '0.4'
  volume: '10'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.48
  scheme: 6x2@75%
  set_inol: '0.08'
  volume: '12'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.48
  scheme: 4x3@75%
  set_inol: '0.12'
  volume: '12'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.48
  scheme: 3x4@75%
  set_inol: '0.16'
  volume: '12'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.48
  scheme: 2x6@75%
  set_inol: '0.24'
  volume: '12'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.56
  scheme: 2x7@75%
  set_inol: '0.28'
  volume: '14'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6
  scheme: 5x3@75%
  set_inol: '0.12'
  volume: '15'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x5@75%
  set_inol: '0.2'
  volume: '15'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.64
  scheme: 4x4@75%
  set_inol: '0.16'
  volume: '16'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.64
  scheme: 2x8@75%
  set_inol: '0.32'
  volume: '16'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.72
  scheme: 6x3@75%
  set_inol: '0.12'
  volume: '18'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.72
  scheme: 3x6@75%
  set_inol: '0.24'
  volume: '18'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.72
  scheme: 2x9@75%
  set_inol: '0.36'
  volume: '18'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 4x5@75%
  set_inol: '0.2'
  volume: '20'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 2x10@75%
  set_inol: '0.4'
  volume: '20'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8400000000000001
  scheme: 3x7@75%
  set_inol: '0.28'
  volume: '21'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.96
  scheme: 6x4@75%
  set_inol: '0.16'
  volume: '24'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.96
  scheme: 4x6@75%
  set_inol: '0.24'
  volume: '24'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.96
  scheme: 3x8@75%
  set_inol: '0.32'
  volume: '24'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.08
  scheme: 3x9@75%
  set_inol: '0.36'
  volume: '27'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.12
  scheme: 4x7@75%
  set_inol: '0.28'
  volume: '28'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.2
  scheme: 5x6@75%
  set_inol: '0.24'
  volume: '30'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x5@75%
  set_inol: '0.2'
  volume: '30'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.2000000000000002
  scheme: 3x10@75%
  set_inol: '0.4'
  volume: '30'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.28
  scheme: 4x8@75%
  set_inol: '0.32'
  volume: '32'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.4000000000000001
  scheme: 5x7@75%
  set_inol: '0.28'
  volume: '35'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.44
  scheme: 6x6@75%
  set_inol: '0.24'
  volume: '36'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.44
  scheme: 4x9@75%
  set_inol: '0.36'
  volume: '36'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.6
  scheme: 5x8@75%
  set_inol: '0.32'
  volume: '40'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.6
  scheme: 4x10@75%
  set_inol: '0.4'
  volume: '40'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.6800000000000002
  scheme: 6x7@75%
  set_inol: '0.28'
  volume: '42'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.7999999999999998
  scheme: 5x9@75%
  set_inol: '0.36'
  volume: '45'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.92
  scheme: 6x8@75%
  set_inol: '0.32'
  volume: '48'
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
