- exercise_inol: 1.2
  scheme: 4x9@70%
  set_inol: '0.3'
  volume: '36'
  week: 1
  weight: '128.8'
  weight_olympic: '129.0'
  weight_powerlifting: '130.0'
- exercise_inol: 1.2
  scheme: 5x6@75%
  set_inol: '0.24'
  volume: '30'
  week: 2
  weight: '138.0'
  weight_olympic: '138.0'
  weight_powerlifting: '137.5'
- exercise_inol: 1.2
  scheme: 4x6@80%
  set_inol: '0.3'
  volume: '24'
  week: 3
  weight: '147.2'
  weight_olympic: '147.0'
  weight_powerlifting: '147.5'
- exercise_inol: 1.2000000000000002
  scheme: 6x3@85%
  set_inol: '0.2'
  volume: '18'
  week: 4
  weight: '156.4'
  weight_olympic: '156.0'
  weight_powerlifting: '157.5'
- exercise_inol: 1.2
  scheme: 4x3@90%
  set_inol: '0.3'
  volume: '12'
  week: 5
  weight: '165.6'
  weight_olympic: '166.0'
  weight_powerlifting: '165.0'
- exercise_inol: 1.2000000000000002
  scheme: 6x1@95%
  set_inol: '0.2'
  volume: '6'
  week: 6
  weight: '174.8'
  weight_olympic: '175.0'
  weight_powerlifting: '175.0'
