- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '125.45'
  weight_olympic: '125.0'
  weight_powerlifting: '125.0'
- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '135.1'
  weight_olympic: '135.0'
  weight_powerlifting: '135.0'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '144.75'
  weight_olympic: '145.0'
  weight_powerlifting: '145.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '154.4'
  weight_olympic: '154.0'
  weight_powerlifting: '155.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '164.05'
  weight_olympic: '164.0'
  weight_powerlifting: '165.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '173.7'
  weight_olympic: '174.0'
  weight_powerlifting: '172.5'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '183.35'
  weight_olympic: '183.0'
  weight_powerlifting: '182.5'
