- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 1
  weight: '121.875'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 0.8
  scheme: 6x4@70%
  set_inol: '0.133333333333'
  volume: '24'
  week: 2
  weight: '131.25'
  weight_olympic: '131.0'
  weight_powerlifting: '132.5'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 3
  weight: '140.625'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 4
  weight: '150.0'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.8
  scheme: 6x2@85%
  set_inol: '0.133333333333'
  volume: '12'
  week: 5
  weight: '159.375'
  weight_olympic: '159.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 6
  weight: '168.75'
  weight_olympic: '169.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 7
  weight: '178.125'
  weight_olympic: '178.0'
  weight_powerlifting: '177.5'
