- exercise_inol: 1.0285714285714285
  scheme: 4x9@65%
  set_inol: '0.257142857143'
  volume: '36'
  week: 1
  weight: '122.2'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 1.0666666666666667
  scheme: 4x8@70%
  set_inol: '0.266666666667'
  volume: '32'
  week: 2
  weight: '131.6'
  weight_olympic: '132.0'
  weight_powerlifting: '132.5'
- exercise_inol: 1.08
  scheme: 3x9@75%
  set_inol: '0.36'
  volume: '27'
  week: 3
  weight: '141.0'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0499999999999998
  scheme: 3x7@80%
  set_inol: '0.35'
  volume: '21'
  week: 4
  weight: '150.4'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
- exercise_inol: 1.0666666666666667
  scheme: 4x4@85%
  set_inol: '0.266666666667'
  volume: '16'
  week: 5
  weight: '159.8'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '169.2'
  weight_olympic: '169.0'
  weight_powerlifting: '170.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '178.6'
  weight_olympic: '179.0'
  weight_powerlifting: '177.5'
