- exercise_inol: 0.8
  scheme: 4x9@55%
  set_inol: '0.2'
  volume: '36'
  week: 1
  weight: '110.0'
  weight_olympic: '110.0'
  weight_powerlifting: '110.0'
- exercise_inol: 0.8
  scheme: 4x8@60%
  set_inol: '0.2'
  volume: '32'
  week: 2
  weight: '120.0'
  weight_olympic: '120.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.8
  scheme: 4x7@65%
  set_inol: '0.2'
  volume: '28'
  week: 3
  weight: '130.0'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.8
  scheme: 4x6@70%
  set_inol: '0.2'
  volume: '24'
  week: 4
  weight: '140.0'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.8
  scheme: 5x4@75%
  set_inol: '0.16'
  volume: '20'
  week: 5
  weight: '150.0'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.8
  scheme: 4x4@80%
  set_inol: '0.2'
  volume: '16'
  week: 6
  weight: '160.0'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 0.8
  scheme: 4x3@85%
  set_inol: '0.2'
  volume: '12'
  week: 7
  weight: '170.0'
  weight_olympic: '170.0'
  weight_powerlifting: '170.0'
- exercise_inol: 0.8
  scheme: 4x2@90%
  set_inol: '0.2'
  volume: '8'
  week: 8
  weight: '180.0'
  weight_olympic: '180.0'
  weight_powerlifting: '180.0'
- exercise_inol: 0.8
  scheme: 4x1@95%
  set_inol: '0.2'
  volume: '4'
  week: 9
  weight: '190.0'
  weight_olympic: '190.0'
  weight_powerlifting: '190.0'
