- exercise_inol: 1.0
  scheme: 5x7@65%
  set_inol: '0.2'
  volume: '35'
  week: 1
  weight: '122.2'
  weight_olympic: '122.0'
  weight_powerlifting: '122.5'
- exercise_inol: 1.0
  scheme: 5x6@70%
  set_inol: '0.2'
  volume: '30'
  week: 2
  weight: '131.6'
  weight_olympic: '132.0'
  weight_powerlifting: '132.5'
- exercise_inol: 1.0
  scheme: 5x5@75%
  set_inol: '0.2'
  volume: '25'
  week: 3
  weight: '141.0'
  weight_olympic: '141.0'
  weight_powerlifting: '140.0'
- exercise_inol: 1.0
  scheme: 5x4@80%
  set_inol: '0.2'
  volume: '20'
  week: 4
  weight: '150.4'
  weight_olympic: '150.0'
  weight_powerlifting: '150.0'
- exercise_inol: 1.0
  scheme: 5x3@85%
  set_inol: '0.2'
  volume: '15'
  week: 5
  weight: '159.8'
  weight_olympic: '160.0'
  weight_powerlifting: '160.0'
- exercise_inol: 1.0
  scheme: 5x2@90%
  set_inol: '0.2'
  volume: '10'
  week: 6
  weight: '169.2'
  weight_olympic: '169.0'
  weight_powerlifting: '170.0'
- exercise_inol: 1.0
  scheme: 5x1@95%
  set_inol: '0.2'
  volume: '5'
  week: 7
  weight: '178.6'
  weight_olympic: '179.0'
  weight_powerlifting: '177.5'
