- exercise_inol: 0.6000000000000001
  scheme: 3x7@65%
  set_inol: '0.2'
  volume: '21'
  week: 1
  weight: '120.9'
  weight_olympic: '121.0'
  weight_powerlifting: '120.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x3@70%
  set_inol: '0.1'
  volume: '18'
  week: 2
  weight: '130.2'
  weight_olympic: '130.0'
  weight_powerlifting: '130.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x5@75%
  set_inol: '0.2'
  volume: '15'
  week: 3
  weight: '139.5'
  weight_olympic: '140.0'
  weight_powerlifting: '140.0'
- exercise_inol: 0.6000000000000001
  scheme: 6x2@80%
  set_inol: '0.1'
  volume: '12'
  week: 4
  weight: '148.8'
  weight_olympic: '149.0'
  weight_powerlifting: '150.0'
- exercise_inol: 0.6000000000000001
  scheme: 3x3@85%
  set_inol: '0.2'
  volume: '9'
  week: 5
  weight: '158.1'
  weight_olympic: '158.0'
  weight_powerlifting: '157.5'
- exercise_inol: 0.6000000000000001
  scheme: 6x1@90%
  set_inol: '0.1'
  volume: '6'
  week: 6
  weight: '167.4'
  weight_olympic: '167.0'
  weight_powerlifting: '167.5'
- exercise_inol: 0.6000000000000001
  scheme: 3x1@95%
  set_inol: '0.2'
  volume: '3'
  week: 7
  weight: '176.7'
  weight_olympic: '177.0'
  weight_powerlifting: '177.5'
